# 世界開発指標 {#wdi-site}

世界銀行（World Bank）の 世界開発指標（WDI）の中の、GDP を使いました。どのようなものか確認しておきましょう。

## 世界銀行（[World Bank](https://www.worldbank.org/en/home)）

* [世界銀行オープンデータ](https://data.worldbank.org)
* [データカタログ](https://datacatalog.worldbank.org/home)
* [世界開発指標（WDI）](https://datatopics.worldbank.org/world-development-indicators/)

世界開発指標は、世界銀行が提供している、オープンデータの一つで、他にも、たくさんのデータを提供しています。三つのサイトのリンクを書きました。一つ一つみていきましょう。

まず、英語を読むことが苦手な場合は、ブラウザー（Google Chrome, Edge, Safari などのホームページ閲覧ソフト）の自動翻訳機能を使うのも良いでしょう。しかし、自動翻訳機能を利用していると、リンク先に飛べなかったり、いくつかの機能が使えないこともありますので、ボタンを押しても、反応しないときは、自動翻訳機能を OFF にして利用してください。

### [世界銀行オープンデータ](https://data.worldbank.org)

上の検索窓の下に、Country と Indicators と書いてあります。

#### 国別サイト

Country（国別）のサイトを選択すると、国のリストが出てきます。

J のところに、Japan（日本）がありますから、選択すると、日本のさまざまな指標とグラフが出てきます。

Indicator（指標）、Most Recent Values（直近の値）、Trend（傾向）が表示されます。指標をクリックすると、大きなグラフが出てきます。その指標のサイトですから、そこで、その指標についての他の国の状況などを確認することができます。そこでは、選択した指標と似た指標が選択できたり、もっと詳しいことをしらべるデータバンクへのリンクもあります。このサイトから、データをダウンロードすることもできるようになっています。

また、国別サイトを開けると、右の方には、地域など、グループに分けてある箇所もあります。その一番下には、World （世界）もありますから、世界全体について見てみたり、収入の階級に分けたサイトの指標を見ることもできるようになっています。


#### 指標別サイト

Indicators（指標）を選択すると、トピックに分けて、指標が並んでいます。

よく見ると、一番上に、Featured Indicators（特徴的な指標） と、All Indicators（すべての指標） となっていて、最初の開いているのは、特徴的な指標の方であることがわかります。すべての指標の方を開けると、たくさんの指標を見ることができます。

トピックは、以下のものに分かれています。

-  Agriculture & Rural Development 農業と農村開発
-  Aid Effectiveness 援助の有効性
-  Climate Change 気候変動
-  Economy & Growth 経済と成長
-  Education 教育
-  Energy & Mining エネルギーと鉱業
-  Environment 環境
-  External Debt 対外債務
-  Financial Sector 金融セクター
-  Gender 性別
-  Health 健康
-  Infrastructure インフラ
-  Poverty 貧困
-  Private Sector 民間部門
-  Public Sector 公共部門
-  Science & Technology 科学技術
-  Social Development 社会開発
-  Social Protection & Labor 社会的保護と労働
-  Trade 貿易
-  Urban Development 都市開発

それぞれの指標を選択すると、グラフが表示される画面が出てきます。それは、上で国別のところから選択したものと同じです。

Indicator Code （WDI コード）は、Details (詳細) を見ると、その指標の概要とともに、書いてあります。
そのデータコードは、そのページの上の URL にも表示されています。


### [データカタログ](https://datacatalog.worldbank.org/home)




### [世界開発指標（WDI）](https://datatopics.worldbank.org/world-development-indicators/)


また、オープンデータについて、世界銀行は、厳密な定義をしています。

### オープンデータの定義（[Open Data Defined](http://opendatatoolkit.worldbank.org/en/essentials.html)）

オープンデータという言葉は、厳密な意味を持っています。データまたはコンテンツは、出所が明示されオープンという性質が維持されれば、誰でも自由に利用、再利用、再配布できるものを言います。

1. データは法的にオープンでなければなりません。つまり、パブリックドメインに置かれ、最小限の制限で自由に使用できなければなりません。

2. データは技術的にオープンでなければなりません。つまり、誰でも自由に使える一般的なソフトウェアツールを使ってデータにアクセスし、機械で読み取ることが可読な電子フォーマットで提供されていなければならなりません。パスワードやファイアウォールによる制限を受けずに、公共のサーバーで、だれでもアクセスできなければなりません。また、オープンデータを見つけやすくするために、さまざまな組織がオープンデータカタログを作成し管理してく必要があります。

<center><font size="3">データはだれのものでしょうか?  パブリックデータのパブリックとは？</font></center>

## 世界開発指標（WDI）

* [World Development Indicators (WDI)](https://datatopics.worldbank.org/world-development-indicators/) : 世界銀行が開発に関する各国間比較可能なデータの集大成である1400の時系列指標（the World Bank’s premier compilation of cross-country comparable data on development; 1400 time series indicators）
  - テーマ別（Themes）: 貧困と格差、人間、環境、経済、国家と市場、グローバルリンク集（Poverty and Inequality, People, Environment, Economy, States and Markets, Global Links）
  - オープンデータとデータバンク（Open Data & DataBank）: Explore data, Query database
  - Bulk Download: Excel, CSV
  - API Documentation
  
### 世界のさまざまな課題

https://datatopics.worldbank.org/world-development-indicators/

1. 貧困と不平等（Poverty and Inequality）：貧困、繁栄、消費、所得分配
2. 人々（People）：人口動態、教育、労働、健康、ジェンダー
3. 環境（Environment）：農業、気候変動、エネルギー、生物多様性、水、衛生
4. 経済（Economy）：成長、経済構造、所得と貯蓄、貿易、労働生産性
5. 国家と市場（States and Markets）：ビジネス、株式市場、軍事、通信、輸送、テクノロジー
6. グローバルリンク（Global Links）：債務、貿易、援助への依存、難民、観光、移住

### ダッシュボード・データの取得・データコード

さまざまな国際機関では、データを、Excel 形式や、CSV (Comma Separated Values）形式などで、提供する以外に、ダッシュボード形式で、グラフを生成するなどして、データを視覚化をある程度できるようにしています。さらに、コンピュータのアプリケーションでデータを直接取得できるように、API (Application Program Interface) を提供しています。

世界開発指標（WDI）は、これらを、すべて統一した形で提供しているために、非常に使いやすいデータベースになっています。また、上にリストしているように、1400余のさまざまなデータを提供しているために、最初に調べてみることをお勧めするデータベースです。

分析を考えると、Excel や、CSV でダウンロードして、それから、データを読み込むよりも、R で直接データを取得する方が、便利ですので、このコースでは、その方法を、説明しています。

データを探すことも、R の中ですることが可能ですが、データベースに慣れるためにも、WDI のホームページから、トピックを選択して、データを探し、説明も調べて、取得したいデータ・コードを調べることも非常に有効です。

いろいろなトピックに、どのような指標があるか調べて、興味のある、データ・コードをリストしてください。データの名前も同時に、記録しておくと良いでしょう。


## 世界銀行以外の国際機関のパブリックデータ

世界銀行以外にも、それぞれの機関がデータを提供しています。どれも、少しずつ使いやすくなってきています。少しずつ、いくつかのデータベースに、アクセスして、できれば、API の利用の仕方も、習得して、データを調べることに少しずつ慣れていっていただければと思います。

下のリストは、私が個人的に、何度か使ったことのある、データベースです。他にも、たくさんのデータベースがありますので、ぜひ、調べてみてください。

* 国際連合　[UNdata](https://data.un.org)
* 経済協力開発機構　[OECD data](https://data.oecd.org)、
* 世界格差データベース（World Inequality Database）[WID](https://wid.world)、
* 欧州連合の統計局　[Eurostat](https://ec.europa.eu/eurostat)、
* データで見る私たちの世界　[Our World in Data](https://ourworldindata.org)

なども、同様の、ダッシュボードを備えており、データの提供もしている。

<p>
日本では、

* [e-Stat](https://www.e-stat.go.jp/)：政府統計の総合窓口 - 統計で見る日本
* [ダッシュボード](https://dashboard.e-stat.go.jp)：対話型形式でのデータの視覚化

## 持続的開発目標（SDGs） データ

* 世界銀行：https://databank.worldbank.org/source/sustainable-development-goals-(sdgs)
* 国連：https://unstats.un.org/sdgs/dataportal/database
* データで見る私たちの世界：Our World in Data SGD Tracker: https://sdg-tracker.org/
* SDG Index: https://dashboards.sdgindex.org/map

## 課題

世界開発指標（WDI）の、データで、調べてみたい データコードをいくつか見つけて、書き出してください。

