# (PART) PART I オープンデータ {.unnumbered}

# オープンデータ {#publicdata-site}

```{r include=FALSE}
library(tidyverse)
library(showtext) 
font_add_google('Noto Sans')
showtext_auto()
```

## 概要

すでに、オープンデータについて、説明をし、その例として、世界銀行の世界開発指標（World Development Indicators (WDI)）の説明をし、その一つである、GDP（Gross Domestic Product 国内総生産）を例にとって、はじめてのデータサイエンスというタイトルで、データサイエンスでは、どのようなことを見ていくのかを見てきました。

第一部では、世界銀行や、経済協力開発機構（OECD）、国際連合（United Nations）などの、国際機関のオープンデータや、日本のデータとして、政府機関統計（e-Stat）の紹介をします。

さらに、実際に、それぞれのサイトのオープンデータを、対話型（Interactive）の、ダッシュボード（dashboard）呼ばれている機能の使い方を紹介しながら、データ自身を見ていきます。

さらに、実際のデータの取得（ダウンロード）にも触れ、それぞれの期間が提供する API（アプリケーションプログラムインターフェース）の活用についても、簡単に触れていきます。

第二部で、R を使ったデータサイエンスについて学びますが、その例においても、いくつかのデータを用いる機会がありますので、その準備としての位置付けです。詳細は、第三部で説明します。

R を使ったデータサイエンスを、早く学びたい方は、この第一部をスキップして、第二部から読んでくださって構いません。しかし、みなさんの中には、R を使うところまでできるかは自信がないけれど、実際のオープンデータを見て、データサイエンスではどのようなことを考えるのかを体験してみたいという方もおられると思い、第一部を書いています。

同時に、実際に、オープンデータを活用して、ある課題について調べるときには、基本的なオープンデータについての知識は有用です。どこに、そのようなデータがあるかを見つけることがたいせつであるとともに、データサイエンスはなんと言っても、理論ではなく、実証的なものですから、実際のデータに触れながら、学んでいくのがたいせつだと考えているからです。

こんなふうに、データがたくさん、公開されているのか、と、そんな感触を持っていただければと思います。

## オープンデータについて

オープンデータについては、すでに、世界銀行の定義をご紹介しました。パブリックデータをいう言葉も使われます。それらの違いなども含めて、AI に聞いてみましょう。

**Q. オープンデータ（Open Data）とか、パブリックデータ（Public Data）と言われるものは、どのようなものですか。定義のようなものと、いくつかの例、さらに、重要視されてきている背景を説明してください。**

**GPT4.** (2023.8.15)

**オープンデータ（Open Data）**とは、誰でも自由に利用、再配布、再利用することができ、制限がない、または限定的な制限だけが存在するデータを指します。オープンデータは一般的には無償で提供され、機械可読形式（たとえばCSV、JSONなど）で利用可能であり、再利用のためのライセンスが明確にされています。

一方、**パブリックデータ（Public Data）**は公共の手段で取得されたデータ、または公共の利益のために公開されるべきデータを指します。これは政府や公共機関、研究機関などが収集したデータで、しばしば公共の利益のために公開されます。

オープンデータとパブリックデータの主な違いは、オープンデータが再利用と再配布の観点から「オープン」であることを強調するのに対し、パブリックデータは単に公開されているだけで、再利用や再配布については必ずしも明示されていないことです。

**例えば**、以下のようなものがあります:

1.  気象データ: 天気予報、気温、風向、風速、降水量など

2.  交通データ: 交通渋滞、駐車場の利用状況、公共交通機関の運行状況など

3.  統計データ: 人口、雇用、健康、教育などのデータ

4.  環境データ: 汚染レベル、森林破壊、気候変動などのデータ

5.  地理データ: 地図、土地利用、地質学的情報など

オープンデータとパブリックデータが重要視されてきた**背景**には、以下の要素があります:

1.  **透明性と説明責任**: データが公開されることで、政府や企業の行動についての透明性が高まり、説明責任が強化されます。

2.  **イノベーションと経済的価値**: データが自由に利用できることで、新たなビジネスモデルや製品、サービスの開発が促進され、経済的価値が創出されます。

3.  **市民参加**: データへのアクセスが提供されることで、市民が社会的・政治的な決定プロセスに参加する機会が増えます。

4.  **社会的・環境的課題の解決**: 大量のデータを解析することで、社会的・環境的な課題をより良く理解し、解決策を見つけることが可能になります。

以上のように、オープンデータとパブリックデータは、透明性、説明責任、イノベーション、市民参加、社会的・環境的課題の解決などの観点から重要性を増しています。

### オープンデータの未来

みなさんは、どのように考えますか。まだ、発展途上で、特に、パブリックデータについては、国によって、考え方も一定ではないように見受けられますが、これから、どのような世界を目指していくのか、データサイエンスは、どのような目的のために必要なのか。みなさんは、なんのために勉強しているのか、上の一つ一つの項目をもとに、周囲のみなさん、友人などと、ディスカッションをしながら、考えていただければと思います。
