# (PART) PART II BASICS {-}
# R on R Studio {#ronrstudio}

```{r include=FALSE}
library(tidyverse)
library(showtext) 
font_add_google('Noto Sans')
showtext_auto()
```

## はじめに

R Studio で R を使うことを始めましょう。

## R と R Studio

> R is a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS. 
> R は、無償で提供されている、統計解析とグラフを描写する環境です。Windows、MacOS や、Linux で利用することが可能です。
https://www.r-project.org

> RStudio is an integrated development environment (IDE) for R and Python. It includes a console, syntax-highlighting editor that supports direct code execution, and tools for plotting, history, debugging, and workspace management. RStudio is available in open source and commercial editions and runs on the desktop (Windows, Mac, and Linux).
> RStudio は、R と Python のための、総合開発環境です。RStudio には、プログラムを実行したり、制御やジョブ管理のための、コンソール（console）、コードを書いたり、実行したりする、文書の編集をする、エディター（Editor）とともに、グラフを表示したり、履歴や、プログラムを修正するなどのための、さまざまなツールが付属しています。RStudio はオープンソースで提供され、Windows、Mac および、Linux で利用可能で、有償版のサービスと無償版を提供しています。
https://posit.co/products/open-source/rstudio/

R は、統計解析のためのシステムで、R Studio は、R（および Python）を利用するための、総合開発環境です。そこで、「R Studio で R を利用する」という表現をします。


## R と R Studio のインストール

R と R Studio をインストールします。

両方とも、インストールすることが必要です。

### R のインストール

https://cloud.r-project.org

上のリンクから、Windows、macOS または、Linux を選択して、インストールしてください。

macOS の場合は、M1, M2 など、最近の Apple Silicon の CPU で動くコンピュータか、以前の、Intel の CPU で動くものか、選択してください。Mac の左上の、りんごマークの、このコンピュータについてから、確認できます。 

不明の場合は、「R のインストール」と検索してみてください。

### R Studio の インストール

http://www.rstudio.com/download

上のリンクから、Windows 10/11 または、macOS 11+ を 選択してください。これら以外の、古いシステムのコンピュータの場合は、 下のサイトから、探してください。

https://docs.posit.co/previous-versions/

不明の場合は、「RStudio のインストール」と検索してみてください。

## プロジェクト - Project

RStudio で R を利用する場合には、プロジェクトを作成することを強く勧めます。

* R Studio の起動
* New Project 
  - Directory を指定してプロジェクトを作成
* 終了
* プロジェクトの起動

## コンソールで実行 - Run in Console

* `head(cars)`
* `str(cars)`
* `summary(cars)`
* `plot(cars)`
* `df <- cars`
* `head(df)`
* `View(cars)`
* `?cars`
* `?datasets`
* `library(help = "datasets")`

おすすめ：`Sys.setenv(LANG = "en")`

## R Studio について

### 四つの窓枠とタブ Four Panes and Tabs

* Top Left: Source Editor
* Top Right: Environment, History, etc.
* Bottom Left: Console, Terminal, Render, Background Jobs
* Bottom Right: Files, Plots, Packages, Help, Viewer, Presentation

## R Script 実行記録

* In RStudio (create Project in RStudio) choose File > New File > R Script
* Choose File > Save As, save with a name; e.g. {file names} (.R will be added automatically)
* To run a code: at the cursor press Ctrl+Shift+Enter (Win) or Cmd+Shift+Enter (Mac).

### Tips

* Top Manu: Help > Keyboard Short Cut Help contains many shortcuts.
* Bottom Right Pane: Check the files by selecting the Files tab.


## パッケージ - Packages

R packages are extensions to the R statistical programming language containing code, data, and documentation in a standardised collection format that can be installed by users of R using Tool > Install Packages in the top menu bar of R Studio.

Rパッケージは、Rの拡張機能で、コード、データ、ドキュメントを標準化されたコレクション形式で含んでおり、標準的なものは、R Studio の Top Bar の Tool > Install Packages からインストールできます。

* `tidyverse`
* `rmarkdown`
* `tinytex`

インストールは一回だけ。ときどき、Tools > Check for Package Update をつかって、Update しておくと良いでしょう。

## クラウド - Posit Cloud

RStudio Cloudは、誰でもオンラインでデータサイエンスを行い、共有し、教え、学ぶことができる、軽量でクラウドベースのソリューションです。

### クラウドサービス　How to Start Posit Cloud

1. Go to https://posit.cloud/
2. Sign Up: top right
3. Email address or Google account
4. New Project: Project Name


## 練習問題 Posit Primers 

Posit Primers https://posit.cloud/learn/primers

### 最初の演習　The Basics – r4ds: Explore, I

* [Visualization Basics](https://rstudio.cloud/learn/primers/1.1)
* [Programming Basics](https://rstudio.cloud/learn/primers/1.2)


## 参考文献 References

* R For Data Science, by H. Wickham: https://r4ds.had.co.nz
  - Introduction: https://r4ds.had.co.nz/explore-intro.html#explore-intro
* Bookdown: https://bookdown.org, [Archive](https://bookdown.org/home/archive/)

  
* [Introducton to R](https://ds-sl.github.io/intro2r/intro2r.nb.html#3_Data_Analysis_Using_RStudio)
* [Data Analysis for Researchers 2022](https://icu-hsuzuki.github.io/da4r2022/)

## YouTube Video - getstarted

<iframe width="560" height="315" src="https://www.youtube.com/embed/9uQmMZoG74g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


