<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Chapter 20 Modeling | データサイエンスをはじめましょう - Data Science for All -</title>

    <meta name="author" content="鈴木寛（Hirosi Suzuki）" />
  
   <meta name="description" content="<p>This is a lecture note using the bookdown package to write a book in Japanese.
The HTML output format for this example is bookdown::bs4_book,
set in the _output.yml file.</p>" />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="Chapter 20 Modeling | データサイエンスをはじめましょう - Data Science for All -" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://icu-hsuzuki.github.io/ds4aj/" />
  
  <meta property="og:description" content="<p>This is a lecture note using the bookdown package to write a book in Japanese.
The HTML output format for this example is bookdown::bs4_book,
set in the _output.yml file.</p>" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 20 Modeling | データサイエンスをはじめましょう - Data Science for All -" />
  
  <meta name="twitter:description" content="<p>This is a lecture note using the bookdown package to write a book in Japanese.
The HTML output format for this example is bookdown::bs4_book,
set in the _output.yml file.</p>" />
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.4.2/transition.js"></script>
    <script src="libs/bs3compat-0.4.2/tabs.js"></script>
    <script src="libs/bs3compat-0.4.2/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">データサイエンスをはじめましょう<br />
- Data Science for All -</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="modeling" class="section level1" number="20">
<h1><span class="header-section-number">Chapter 20</span> Modeling</h1>
<div id="setup-1" class="section level3 unnumbered">
<h3>Setup</h3>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="modeling.html#cb197-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb197-2"><a href="modeling.html#cb197-2" tabindex="-1"></a><span class="co">#&gt; ── Attaching core tidyverse packages ──── tidyverse 2.0.0 ──</span></span>
<span id="cb197-3"><a href="modeling.html#cb197-3" tabindex="-1"></a><span class="co">#&gt; ✔ dplyr     1.1.2     ✔ readr     2.1.4</span></span>
<span id="cb197-4"><a href="modeling.html#cb197-4" tabindex="-1"></a><span class="co">#&gt; ✔ forcats   1.0.0     ✔ stringr   1.5.0</span></span>
<span id="cb197-5"><a href="modeling.html#cb197-5" tabindex="-1"></a><span class="co">#&gt; ✔ ggplot2   3.4.2     ✔ tibble    3.2.1</span></span>
<span id="cb197-6"><a href="modeling.html#cb197-6" tabindex="-1"></a><span class="co">#&gt; ✔ lubridate 1.9.2     ✔ tidyr     1.3.0</span></span>
<span id="cb197-7"><a href="modeling.html#cb197-7" tabindex="-1"></a><span class="co">#&gt; ✔ purrr     1.0.1     </span></span>
<span id="cb197-8"><a href="modeling.html#cb197-8" tabindex="-1"></a><span class="co">#&gt; ── Conflicts ────────────────────── tidyverse_conflicts() ──</span></span>
<span id="cb197-9"><a href="modeling.html#cb197-9" tabindex="-1"></a><span class="co">#&gt; ✖ dplyr::filter() masks stats::filter()</span></span>
<span id="cb197-10"><a href="modeling.html#cb197-10" tabindex="-1"></a><span class="co">#&gt; ✖ dplyr::lag()    masks stats::lag()</span></span>
<span id="cb197-11"><a href="modeling.html#cb197-11" tabindex="-1"></a><span class="co">#&gt; ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</span></span>
<span id="cb197-12"><a href="modeling.html#cb197-12" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb197-13"><a href="modeling.html#cb197-13" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb197-14"><a href="modeling.html#cb197-14" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code></pre></div>
<ul>
<li>broom: <a href="https://cran.r-project.org/web/packages/broom/index.html" class="uri">https://cran.r-project.org/web/packages/broom/index.html</a></li>
<li>Introduction to broom: <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a></li>
</ul>
</div>
<div id="what-is-modeling-in-eda" class="section level2" number="20.1">
<h2><span class="header-section-number">20.1</span> What is modeling in EDA</h2>
<p>Model is a simple summary of data</p>
<p>Goal: A simple low-dimensional summary of a dataset. Ideally, the model will capture true “signals” (i.e. patterns generated by the phenomenon of interest), and ignore “noise” (i.e. random variation that you’re not interested in).</p>
<div class="float">
<img src="data/data-science.png" alt="image" />
<div class="figcaption">image</div>
</div>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="modeling.html#cb198-1" tabindex="-1"></a>df0 <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(iris) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species <span class="sc">!=</span> <span class="st">&quot;setosa&quot;</span>)</span></code></pre></div>
<p>Let us look at two charts.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="modeling.html#cb199-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Petal.Width, Petal.Length)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="modeling.html#cb200-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Petal.Width, Petal.Length)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>,<span class="at">formula=</span>y<span class="sc">~</span>x, <span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="modeling.html#cb201-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sepal.Width, Sepal.Length)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="modeling.html#cb202-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sepal.Width, Sepal.Length)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>,<span class="at">formula=</span>y<span class="sc">~</span>x, <span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="linear-model-petal.length-petal.width" class="section level2" number="20.2">
<h2><span class="header-section-number">20.2</span> Linear Model: Petal.Length ~ Petal.Width</h2>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="modeling.html#cb203-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width, .)</span>
<span id="cb203-2"><a href="modeling.html#cb203-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb203-3"><a href="modeling.html#cb203-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb203-4"><a href="modeling.html#cb203-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = Petal.Length ~ Petal.Width, data = .)</span></span>
<span id="cb203-5"><a href="modeling.html#cb203-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb203-6"><a href="modeling.html#cb203-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb203-7"><a href="modeling.html#cb203-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)  Petal.Width  </span></span>
<span id="cb203-8"><a href="modeling.html#cb203-8" tabindex="-1"></a><span class="co">#&gt;       2.224        1.600</span></span></code></pre></div>
</div>
<div id="formula-textpetal.length-2.224-1.600cdot-textpetal.width" class="section level2" number="20.3">
<h2><span class="header-section-number">20.3</span> Formula: <span class="math inline">\(\text{Petal.Length} = 2.224 + 1.600\cdot \text{Petal.Width}\)</span></h2>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="linear-model-sepal.length-sepal.width" class="section level2" number="20.4">
<h2><span class="header-section-number">20.4</span> Linear Model: Sepal.Length ~ Sepal.Width</h2>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="modeling.html#cb204-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Sepal.Width, .)</span>
<span id="cb204-2"><a href="modeling.html#cb204-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb204-3"><a href="modeling.html#cb204-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb204-4"><a href="modeling.html#cb204-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = Sepal.Length ~ Sepal.Width, data = .)</span></span>
<span id="cb204-5"><a href="modeling.html#cb204-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb204-6"><a href="modeling.html#cb204-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb204-7"><a href="modeling.html#cb204-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)  Sepal.Width  </span></span>
<span id="cb204-8"><a href="modeling.html#cb204-8" tabindex="-1"></a><span class="co">#&gt;       3.093        1.103</span></span></code></pre></div>
</div>
<div id="formula-textsepal.length-3.093-1.103cdot-textsepal.width" class="section level2" number="20.5">
<h2><span class="header-section-number">20.5</span> Formula: <span class="math inline">\(\text{Sepal.Length} = 3.093 + 1.103\cdot \text{Sepal.Width}\)</span></h2>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="petal.length-petal.width-r-squared-0.6779---68" class="section level2" number="20.6">
<h2><span class="header-section-number">20.6</span> Petal.Length ~ Petal.Width: R squared = 0.6779 - 68%</h2>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="modeling.html#cb205-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width, .) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb205-2"><a href="modeling.html#cb205-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb205-3"><a href="modeling.html#cb205-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb205-4"><a href="modeling.html#cb205-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = Petal.Length ~ Petal.Width, data = .)</span></span>
<span id="cb205-5"><a href="modeling.html#cb205-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb205-6"><a href="modeling.html#cb205-6" tabindex="-1"></a><span class="co">#&gt; Residuals:</span></span>
<span id="cb205-7"><a href="modeling.html#cb205-7" tabindex="-1"></a><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span id="cb205-8"><a href="modeling.html#cb205-8" tabindex="-1"></a><span class="co">#&gt; -0.9842 -0.3043 -0.1043  0.2407  1.2755 </span></span>
<span id="cb205-9"><a href="modeling.html#cb205-9" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb205-10"><a href="modeling.html#cb205-10" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb205-11"><a href="modeling.html#cb205-11" tabindex="-1"></a><span class="co">#&gt;             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb205-12"><a href="modeling.html#cb205-12" tabindex="-1"></a><span class="co">#&gt; (Intercept)   2.2240     0.1926   11.55   &lt;2e-16 ***</span></span>
<span id="cb205-13"><a href="modeling.html#cb205-13" tabindex="-1"></a><span class="co">#&gt; Petal.Width   1.6003     0.1114   14.36   &lt;2e-16 ***</span></span>
<span id="cb205-14"><a href="modeling.html#cb205-14" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb205-15"><a href="modeling.html#cb205-15" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  </span></span>
<span id="cb205-16"><a href="modeling.html#cb205-16" tabindex="-1"></a><span class="co">#&gt; 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb205-17"><a href="modeling.html#cb205-17" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb205-18"><a href="modeling.html#cb205-18" tabindex="-1"></a><span class="co">#&gt; Residual standard error: 0.4709 on 98 degrees of freedom</span></span>
<span id="cb205-19"><a href="modeling.html#cb205-19" tabindex="-1"></a><span class="co">#&gt; Multiple R-squared:  0.6779, Adjusted R-squared:  0.6746 </span></span>
<span id="cb205-20"><a href="modeling.html#cb205-20" tabindex="-1"></a><span class="co">#&gt; F-statistic: 206.3 on 1 and 98 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div>
</div>
<div id="sepal.length-sepal.width-r-squared-0.3068---31" class="section level2" number="20.7">
<h2><span class="header-section-number">20.7</span> Sepal.Length ~ Sepal.Width: R squared = 0.3068 - 31%</h2>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="modeling.html#cb206-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Sepal.Width, .) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb206-2"><a href="modeling.html#cb206-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb206-3"><a href="modeling.html#cb206-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb206-4"><a href="modeling.html#cb206-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = Sepal.Length ~ Sepal.Width, data = .)</span></span>
<span id="cb206-5"><a href="modeling.html#cb206-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb206-6"><a href="modeling.html#cb206-6" tabindex="-1"></a><span class="co">#&gt; Residuals:</span></span>
<span id="cb206-7"><a href="modeling.html#cb206-7" tabindex="-1"></a><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span id="cb206-8"><a href="modeling.html#cb206-8" tabindex="-1"></a><span class="co">#&gt; -1.0032 -0.3877 -0.0774  0.3200  1.7381 </span></span>
<span id="cb206-9"><a href="modeling.html#cb206-9" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb206-10"><a href="modeling.html#cb206-10" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb206-11"><a href="modeling.html#cb206-11" tabindex="-1"></a><span class="co">#&gt;             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb206-12"><a href="modeling.html#cb206-12" tabindex="-1"></a><span class="co">#&gt; (Intercept)   3.0934     0.4844   6.387 5.70e-09 ***</span></span>
<span id="cb206-13"><a href="modeling.html#cb206-13" tabindex="-1"></a><span class="co">#&gt; Sepal.Width   1.1033     0.1675   6.585 2.27e-09 ***</span></span>
<span id="cb206-14"><a href="modeling.html#cb206-14" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb206-15"><a href="modeling.html#cb206-15" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  </span></span>
<span id="cb206-16"><a href="modeling.html#cb206-16" tabindex="-1"></a><span class="co">#&gt; 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb206-17"><a href="modeling.html#cb206-17" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb206-18"><a href="modeling.html#cb206-18" tabindex="-1"></a><span class="co">#&gt; Residual standard error: 0.5547 on 98 degrees of freedom</span></span>
<span id="cb206-19"><a href="modeling.html#cb206-19" tabindex="-1"></a><span class="co">#&gt; Multiple R-squared:  0.3068, Adjusted R-squared:  0.2997 </span></span>
<span id="cb206-20"><a href="modeling.html#cb206-20" tabindex="-1"></a><span class="co">#&gt; F-statistic: 43.36 on 1 and 98 DF,  p-value: 2.27e-09</span></span></code></pre></div>
</div>
<div id="linear-model-basics-y-x" class="section level2" number="20.8">
<h2><span class="header-section-number">20.8</span> Linear Model Basics: y ~ x</h2>
<pre><code>lm(y~x, data)</code></pre>
<pre><code>data %&gt;% lm(y~x, .)</code></pre>
<p>y-intercept, and slope: rate of increase or decrease</p>
<pre><code>summary(lm(y~x, data))</code></pre>
<pre><code>data %&gt;% lm(y~x, .) %&gt;% summary()</code></pre>
<p>(Multiple) R Squared: a value between 0 and 1, the model’s strength. It is a measurement of the model quality. If the value is close to 1, the model quality is high. If it is close to 0, the model quality is low.</p>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="modeling.html#cb211-1" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="dv">2</span>, <span class="fl">1.5</span>))</span>
<span id="cb211-2"><a href="modeling.html#cb211-2" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(df1<span class="sc">$</span>y)</span>
<span id="cb211-3"><a href="modeling.html#cb211-3" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x, df1)</span>
<span id="cb211-4"><a href="modeling.html#cb211-4" tabindex="-1"></a><span class="fu">augment</span>(mod1) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(x,y)) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(x,y), <span class="at">formula =</span> y<span class="sc">~</span>x, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> ybar, <span class="at">linetype=</span><span class="st">&quot;longdash&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(x, ybar), <span class="at">shape=</span><span class="dv">4</span>) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(x, .fitted), <span class="at">shape =</span><span class="dv">9</span>, <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(x, ybar, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">&quot;(&quot;</span>,x,<span class="st">&quot;,&quot;</span>,<span class="fl">1.25</span>,<span class="st">&quot;)&quot;</span>)), <span class="at">nudge_y =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(x, .fitted, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">&quot;(&quot;</span>,x,<span class="st">&quot;,&quot;</span>,.fitted,<span class="st">&quot;)&quot;</span>)), <span class="at">nudge_y =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(x, y, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">&quot;(&quot;</span>,x,<span class="st">&quot;,&quot;</span>,y,<span class="st">&quot;)&quot;</span>)), <span class="at">nudge_y =</span> <span class="sc">-</span><span class="fl">0.1</span>) </span></code></pre></div>
<ul>
<li><span class="math inline">\((x_1, y_1)\)</span>, <span class="math inline">\((x_2,y_2)\)</span>, <span class="math inline">\((x_3, y_3)\)</span>, <span class="math inline">\((x_4, y_4)\)</span>: Data points</li>
<li><span class="math inline">\(\bar{y}\)</span>: mean of y = <span class="math inline">\((y_1 + y_2 + y_3 + y_4)/4\)</span>.</li>
<li><span class="math inline">\(\hat{y}_i\)</span>: prediction at <span class="math inline">\(x_i\)</span>,
<ul>
<li><span class="math inline">\((x_1, \hat{y}_1)\)</span>, <span class="math inline">\((x_2, \hat{y}_2)\)</span>, <span class="math inline">\((x_3, \hat{y}_3)\)</span>, <span class="math inline">\((x_4, \hat{y}_4)\)</span> are on the regression line.</li>
</ul></li>
<li><span class="math inline">\(y_1-\hat{y}_1\)</span>, <span class="math inline">\(y_2-\hat{y}_2\)</span>, <span class="math inline">\(y_2-\hat{y}_2\)</span>, <span class="math inline">\(y_2-\hat{y}_2\)</span> are called residues.</li>
</ul>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="r-squared" class="section level2" number="20.9">
<h2><span class="header-section-number">20.9</span> R Squared</h2>
<p><span class="math display">\[SS_{tot} = (1-1.25)^2 + (0.5-1.25)^2 + (2-1.25)^2 + (1.5-1.25)^2 = 1.25\]</span>
<span class="math display">\[SS_{res} = (1-0.8)^2 + (0.5-1.1)^2 + (2-1.4)^2 + (1.5-1.7)^2 = 0.8\]</span>
<span class="math display">\[R^2 = 1 - \frac{SS_{res}}{SS_{tot}} = 1- \frac{0.8}{1.25} = 0.36.\]</span></p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="modeling.html#cb212-1" tabindex="-1"></a><span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared</span>
<span id="cb212-2"><a href="modeling.html#cb212-2" tabindex="-1"></a><span class="co">#&gt; [1] 0.36</span></span></code></pre></div>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="modeling.html#cb213-1" tabindex="-1"></a>mod1 <span class="sc">%&gt;%</span> <span class="fu">glance</span>() <span class="sc">%&gt;%</span> <span class="fu">pull</span>(r.squared)</span>
<span id="cb213-2"><a href="modeling.html#cb213-2" tabindex="-1"></a><span class="co">#&gt; [1] 0.36</span></span></code></pre></div>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="modeling.html#cb214-1" tabindex="-1"></a>mod1 <span class="sc">%&gt;%</span> <span class="fu">glance</span>() <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="st">`</span><span class="at">R Squared</span><span class="st">`</span> <span class="ot">=</span> r.squared)</span>
<span id="cb214-2"><a href="modeling.html#cb214-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1 × 1</span></span>
<span id="cb214-3"><a href="modeling.html#cb214-3" tabindex="-1"></a><span class="co">#&gt;   `R Squared`</span></span>
<span id="cb214-4"><a href="modeling.html#cb214-4" tabindex="-1"></a><span class="co">#&gt;         &lt;dbl&gt;</span></span>
<span id="cb214-5"><a href="modeling.html#cb214-5" tabindex="-1"></a><span class="co">#&gt; 1        0.36</span></span></code></pre></div>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="modeling.html#cb215-1" tabindex="-1"></a>mod1 <span class="sc">%&gt;%</span> <span class="fu">summary</span>() <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span>
<span id="cb215-2"><a href="modeling.html#cb215-2" tabindex="-1"></a><span class="co">#&gt; List of 11</span></span>
<span id="cb215-3"><a href="modeling.html#cb215-3" tabindex="-1"></a><span class="co">#&gt;  $ call         : language lm(formula = y ~ x, data = df1)</span></span>
<span id="cb215-4"><a href="modeling.html#cb215-4" tabindex="-1"></a><span class="co">#&gt;  $ terms        :Classes &#39;terms&#39;, &#39;formula&#39;  language y ~ x</span></span>
<span id="cb215-5"><a href="modeling.html#cb215-5" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;variables&quot;)= language list(y, x)</span></span>
<span id="cb215-6"><a href="modeling.html#cb215-6" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;factors&quot;)= int [1:2, 1] 0 1</span></span>
<span id="cb215-7"><a href="modeling.html#cb215-7" tabindex="-1"></a><span class="co">#&gt;   .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2</span></span>
<span id="cb215-8"><a href="modeling.html#cb215-8" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;term.labels&quot;)= chr &quot;x&quot;</span></span>
<span id="cb215-9"><a href="modeling.html#cb215-9" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;order&quot;)= int 1</span></span>
<span id="cb215-10"><a href="modeling.html#cb215-10" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;intercept&quot;)= int 1</span></span>
<span id="cb215-11"><a href="modeling.html#cb215-11" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;response&quot;)= int 1</span></span>
<span id="cb215-12"><a href="modeling.html#cb215-12" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; </span></span>
<span id="cb215-13"><a href="modeling.html#cb215-13" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;predvars&quot;)= language list(y, x)</span></span>
<span id="cb215-14"><a href="modeling.html#cb215-14" tabindex="-1"></a><span class="co">#&gt;   .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:2] &quot;numeric&quot; &quot;numeric&quot;</span></span>
<span id="cb215-15"><a href="modeling.html#cb215-15" tabindex="-1"></a><span class="co">#&gt;   .. .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;y&quot; &quot;x&quot;</span></span>
<span id="cb215-16"><a href="modeling.html#cb215-16" tabindex="-1"></a><span class="co">#&gt;  $ residuals    : Named num [1:4] 0.2 -0.6 0.6 -0.2</span></span>
<span id="cb215-17"><a href="modeling.html#cb215-17" tabindex="-1"></a><span class="co">#&gt;   ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot;</span></span>
<span id="cb215-18"><a href="modeling.html#cb215-18" tabindex="-1"></a><span class="co">#&gt;  $ coefficients : num [1:2, 1:4] 0.5 0.3 0.775 0.283 0.645 ...</span></span>
<span id="cb215-19"><a href="modeling.html#cb215-19" tabindex="-1"></a><span class="co">#&gt;   ..- attr(*, &quot;dimnames&quot;)=List of 2</span></span>
<span id="cb215-20"><a href="modeling.html#cb215-20" tabindex="-1"></a><span class="co">#&gt;   .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;x&quot;</span></span>
<span id="cb215-21"><a href="modeling.html#cb215-21" tabindex="-1"></a><span class="co">#&gt;   .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot; &quot;Pr(&gt;|t|)&quot;</span></span>
<span id="cb215-22"><a href="modeling.html#cb215-22" tabindex="-1"></a><span class="co">#&gt;  $ aliased      : Named logi [1:2] FALSE FALSE</span></span>
<span id="cb215-23"><a href="modeling.html#cb215-23" tabindex="-1"></a><span class="co">#&gt;   ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;(Intercept)&quot; &quot;x&quot;</span></span>
<span id="cb215-24"><a href="modeling.html#cb215-24" tabindex="-1"></a><span class="co">#&gt;  $ sigma        : num 0.632</span></span>
<span id="cb215-25"><a href="modeling.html#cb215-25" tabindex="-1"></a><span class="co">#&gt;  $ df           : int [1:3] 2 2 2</span></span>
<span id="cb215-26"><a href="modeling.html#cb215-26" tabindex="-1"></a><span class="co">#&gt;  $ r.squared    : num 0.36</span></span>
<span id="cb215-27"><a href="modeling.html#cb215-27" tabindex="-1"></a><span class="co">#&gt;  $ adj.r.squared: num 0.04</span></span>
<span id="cb215-28"><a href="modeling.html#cb215-28" tabindex="-1"></a><span class="co">#&gt;  $ fstatistic   : Named num [1:3] 1.12 1 2</span></span>
<span id="cb215-29"><a href="modeling.html#cb215-29" tabindex="-1"></a><span class="co">#&gt;   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;</span></span>
<span id="cb215-30"><a href="modeling.html#cb215-30" tabindex="-1"></a><span class="co">#&gt;  $ cov.unscaled : num [1:2, 1:2] 1.5 -0.5 -0.5 0.2</span></span>
<span id="cb215-31"><a href="modeling.html#cb215-31" tabindex="-1"></a><span class="co">#&gt;   ..- attr(*, &quot;dimnames&quot;)=List of 2</span></span>
<span id="cb215-32"><a href="modeling.html#cb215-32" tabindex="-1"></a><span class="co">#&gt;   .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;x&quot;</span></span>
<span id="cb215-33"><a href="modeling.html#cb215-33" tabindex="-1"></a><span class="co">#&gt;   .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;x&quot;</span></span>
<span id="cb215-34"><a href="modeling.html#cb215-34" tabindex="-1"></a><span class="co">#&gt;  - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</span></span></code></pre></div>
</div>
<div id="useful-mathematical-formula" class="section level2" number="20.10">
<h2><span class="header-section-number">20.10</span> Useful Mathematical Formula</h2>
<ul>
<li>Let <span class="math inline">\(x = c(x_1, x_2, \ldots, x_n)\)</span> be the independent variable, i.e., Sepal.L</li>
<li>Let <span class="math inline">\(y = c(y_1, y_2, \ldots, y_n)\)</span> be the dependent variable, i.e., Sepal.W</li>
<li>Let <span class="math inline">\(\mbox{pred} = c(\hat{y}_1, \hat{y}_2, \ldots, \hat{y}_n)\)</span> be the predicted values by linear regression.</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\mbox{slope of the regression line}  &amp;= \frac{cov(x,y)}{var(x)} = \frac{cor(x,y)\sqrt{var(y)}}{\sqrt{var(x)}}\\
\mbox{total sum of squares} &amp;= SS_{tot} = \sum_{i}(y_i-mean(y))^2\\
\mbox{residual sum of squares} &amp;= SS_{res} = \sum_{i}(y_i-\mbox{pred}_i)^2 = \sum_{i}(y_i-\hat{y}_i)^2\\
\mbox{R squared} = R^2 &amp; = 1 - \frac{SS_{res}}{SS_{tot}} = cor(x,y)^2
\end{aligned}
\]</span></p>
<div id="adjusted-r-squared" class="section level3" number="20.10.1">
<h3><span class="header-section-number">20.10.1</span> Adjusted R Squared</h3>
<p><span class="math display">\[\text{Adjusted }R^2 = 1- \frac{(1-R^2)(n-1)}{n-k-1}\]</span>
<span class="math inline">\(n\)</span>: number of observations, the number of rows</p>
<p><span class="math inline">\(k\)</span>: number of variables used for prediction</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="modeling.html#cb216-1" tabindex="-1"></a>df0 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span>
<span id="cb216-2"><a href="modeling.html#cb216-2" tabindex="-1"></a><span class="co">#&gt;              Sepal.Length Sepal.Width Petal.Length</span></span>
<span id="cb216-3"><a href="modeling.html#cb216-3" tabindex="-1"></a><span class="co">#&gt; Sepal.Length    1.0000000   0.5538548    0.8284787</span></span>
<span id="cb216-4"><a href="modeling.html#cb216-4" tabindex="-1"></a><span class="co">#&gt; Sepal.Width     0.5538548   1.0000000    0.5198023</span></span>
<span id="cb216-5"><a href="modeling.html#cb216-5" tabindex="-1"></a><span class="co">#&gt; Petal.Length    0.8284787   0.5198023    1.0000000</span></span>
<span id="cb216-6"><a href="modeling.html#cb216-6" tabindex="-1"></a><span class="co">#&gt; Petal.Width     0.5937094   0.5662025    0.8233476</span></span>
<span id="cb216-7"><a href="modeling.html#cb216-7" tabindex="-1"></a><span class="co">#&gt;              Petal.Width</span></span>
<span id="cb216-8"><a href="modeling.html#cb216-8" tabindex="-1"></a><span class="co">#&gt; Sepal.Length   0.5937094</span></span>
<span id="cb216-9"><a href="modeling.html#cb216-9" tabindex="-1"></a><span class="co">#&gt; Sepal.Width    0.5662025</span></span>
<span id="cb216-10"><a href="modeling.html#cb216-10" tabindex="-1"></a><span class="co">#&gt; Petal.Length   0.8233476</span></span>
<span id="cb216-11"><a href="modeling.html#cb216-11" tabindex="-1"></a><span class="co">#&gt; Petal.Width    1.0000000</span></span></code></pre></div>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="modeling.html#cb217-1" tabindex="-1"></a>cormat <span class="ot">&lt;-</span> df0 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span>
<span id="cb217-2"><a href="modeling.html#cb217-2" tabindex="-1"></a>cormat<span class="sc">*</span>cormat</span>
<span id="cb217-3"><a href="modeling.html#cb217-3" tabindex="-1"></a><span class="co">#&gt;              Sepal.Length Sepal.Width Petal.Length</span></span>
<span id="cb217-4"><a href="modeling.html#cb217-4" tabindex="-1"></a><span class="co">#&gt; Sepal.Length    1.0000000   0.3067552    0.6863769</span></span>
<span id="cb217-5"><a href="modeling.html#cb217-5" tabindex="-1"></a><span class="co">#&gt; Sepal.Width     0.3067552   1.0000000    0.2701944</span></span>
<span id="cb217-6"><a href="modeling.html#cb217-6" tabindex="-1"></a><span class="co">#&gt; Petal.Length    0.6863769   0.2701944    1.0000000</span></span>
<span id="cb217-7"><a href="modeling.html#cb217-7" tabindex="-1"></a><span class="co">#&gt; Petal.Width     0.3524909   0.3205853    0.6779013</span></span>
<span id="cb217-8"><a href="modeling.html#cb217-8" tabindex="-1"></a><span class="co">#&gt;              Petal.Width</span></span>
<span id="cb217-9"><a href="modeling.html#cb217-9" tabindex="-1"></a><span class="co">#&gt; Sepal.Length   0.3524909</span></span>
<span id="cb217-10"><a href="modeling.html#cb217-10" tabindex="-1"></a><span class="co">#&gt; Sepal.Width    0.3205853</span></span>
<span id="cb217-11"><a href="modeling.html#cb217-11" tabindex="-1"></a><span class="co">#&gt; Petal.Length   0.6779013</span></span>
<span id="cb217-12"><a href="modeling.html#cb217-12" tabindex="-1"></a><span class="co">#&gt; Petal.Width    1.0000000</span></span></code></pre></div>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="modeling.html#cb218-1" tabindex="-1"></a><span class="fu">as_tibble</span>(iris) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;setosa&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span>
<span id="cb218-2"><a href="modeling.html#cb218-2" tabindex="-1"></a><span class="co">#&gt;              Sepal.Length Sepal.Width Petal.Length</span></span>
<span id="cb218-3"><a href="modeling.html#cb218-3" tabindex="-1"></a><span class="co">#&gt; Sepal.Length    1.0000000   0.7425467    0.2671758</span></span>
<span id="cb218-4"><a href="modeling.html#cb218-4" tabindex="-1"></a><span class="co">#&gt; Sepal.Width     0.7425467   1.0000000    0.1777000</span></span>
<span id="cb218-5"><a href="modeling.html#cb218-5" tabindex="-1"></a><span class="co">#&gt; Petal.Length    0.2671758   0.1777000    1.0000000</span></span>
<span id="cb218-6"><a href="modeling.html#cb218-6" tabindex="-1"></a><span class="co">#&gt; Petal.Width     0.2780984   0.2327520    0.3316300</span></span>
<span id="cb218-7"><a href="modeling.html#cb218-7" tabindex="-1"></a><span class="co">#&gt;              Petal.Width</span></span>
<span id="cb218-8"><a href="modeling.html#cb218-8" tabindex="-1"></a><span class="co">#&gt; Sepal.Length   0.2780984</span></span>
<span id="cb218-9"><a href="modeling.html#cb218-9" tabindex="-1"></a><span class="co">#&gt; Sepal.Width    0.2327520</span></span>
<span id="cb218-10"><a href="modeling.html#cb218-10" tabindex="-1"></a><span class="co">#&gt; Petal.Length   0.3316300</span></span>
<span id="cb218-11"><a href="modeling.html#cb218-11" tabindex="-1"></a><span class="co">#&gt; Petal.Width    1.0000000</span></span></code></pre></div>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="modeling.html#cb219-1" tabindex="-1"></a><span class="fu">as_tibble</span>(iris) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;virginica&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span>
<span id="cb219-2"><a href="modeling.html#cb219-2" tabindex="-1"></a><span class="co">#&gt;              Sepal.Length Sepal.Width Petal.Length</span></span>
<span id="cb219-3"><a href="modeling.html#cb219-3" tabindex="-1"></a><span class="co">#&gt; Sepal.Length    1.0000000   0.4572278    0.8642247</span></span>
<span id="cb219-4"><a href="modeling.html#cb219-4" tabindex="-1"></a><span class="co">#&gt; Sepal.Width     0.4572278   1.0000000    0.4010446</span></span>
<span id="cb219-5"><a href="modeling.html#cb219-5" tabindex="-1"></a><span class="co">#&gt; Petal.Length    0.8642247   0.4010446    1.0000000</span></span>
<span id="cb219-6"><a href="modeling.html#cb219-6" tabindex="-1"></a><span class="co">#&gt; Petal.Width     0.2811077   0.5377280    0.3221082</span></span>
<span id="cb219-7"><a href="modeling.html#cb219-7" tabindex="-1"></a><span class="co">#&gt;              Petal.Width</span></span>
<span id="cb219-8"><a href="modeling.html#cb219-8" tabindex="-1"></a><span class="co">#&gt; Sepal.Length   0.2811077</span></span>
<span id="cb219-9"><a href="modeling.html#cb219-9" tabindex="-1"></a><span class="co">#&gt; Sepal.Width    0.5377280</span></span>
<span id="cb219-10"><a href="modeling.html#cb219-10" tabindex="-1"></a><span class="co">#&gt; Petal.Length   0.3221082</span></span>
<span id="cb219-11"><a href="modeling.html#cb219-11" tabindex="-1"></a><span class="co">#&gt; Petal.Width    1.0000000</span></span></code></pre></div>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="modeling.html#cb220-1" tabindex="-1"></a><span class="fu">as_tibble</span>(iris) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;versicolor&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span>
<span id="cb220-2"><a href="modeling.html#cb220-2" tabindex="-1"></a><span class="co">#&gt;              Sepal.Length Sepal.Width Petal.Length</span></span>
<span id="cb220-3"><a href="modeling.html#cb220-3" tabindex="-1"></a><span class="co">#&gt; Sepal.Length    1.0000000   0.5259107    0.7540490</span></span>
<span id="cb220-4"><a href="modeling.html#cb220-4" tabindex="-1"></a><span class="co">#&gt; Sepal.Width     0.5259107   1.0000000    0.5605221</span></span>
<span id="cb220-5"><a href="modeling.html#cb220-5" tabindex="-1"></a><span class="co">#&gt; Petal.Length    0.7540490   0.5605221    1.0000000</span></span>
<span id="cb220-6"><a href="modeling.html#cb220-6" tabindex="-1"></a><span class="co">#&gt; Petal.Width     0.5464611   0.6639987    0.7866681</span></span>
<span id="cb220-7"><a href="modeling.html#cb220-7" tabindex="-1"></a><span class="co">#&gt;              Petal.Width</span></span>
<span id="cb220-8"><a href="modeling.html#cb220-8" tabindex="-1"></a><span class="co">#&gt; Sepal.Length   0.5464611</span></span>
<span id="cb220-9"><a href="modeling.html#cb220-9" tabindex="-1"></a><span class="co">#&gt; Sepal.Width    0.6639987</span></span>
<span id="cb220-10"><a href="modeling.html#cb220-10" tabindex="-1"></a><span class="co">#&gt; Petal.Length   0.7866681</span></span>
<span id="cb220-11"><a href="modeling.html#cb220-11" tabindex="-1"></a><span class="co">#&gt; Petal.Width    1.0000000</span></span></code></pre></div>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="modeling.html#cb221-1" tabindex="-1"></a><span class="fu">as_tibble</span>(iris) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;virginica&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sepal.Length, Petal.Length)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y<span class="sc">~</span>x, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="modeling.html#cb222-1" tabindex="-1"></a><span class="fu">as_tibble</span>(iris) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;virginica&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length, .) <span class="sc">%&gt;%</span> <span class="fu">glance</span>() <span class="sc">%&gt;%</span> <span class="fu">pull</span>(r.squared) <span class="sc">%&gt;%</span> <span class="fu">sqrt</span>()</span>
<span id="cb222-2"><a href="modeling.html#cb222-2" tabindex="-1"></a><span class="co">#&gt; [1] 0.8642247</span></span></code></pre></div>
<p>Correlations of the data suggest the possible strength of linear model y ~ x.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="modeling.html#cb223-1" tabindex="-1"></a>iris <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span>
<span id="cb223-2"><a href="modeling.html#cb223-2" tabindex="-1"></a><span class="co">#&gt;              Sepal.Length Sepal.Width Petal.Length</span></span>
<span id="cb223-3"><a href="modeling.html#cb223-3" tabindex="-1"></a><span class="co">#&gt; Sepal.Length    1.0000000  -0.1175698    0.8717538</span></span>
<span id="cb223-4"><a href="modeling.html#cb223-4" tabindex="-1"></a><span class="co">#&gt; Sepal.Width    -0.1175698   1.0000000   -0.4284401</span></span>
<span id="cb223-5"><a href="modeling.html#cb223-5" tabindex="-1"></a><span class="co">#&gt; Petal.Length    0.8717538  -0.4284401    1.0000000</span></span>
<span id="cb223-6"><a href="modeling.html#cb223-6" tabindex="-1"></a><span class="co">#&gt; Petal.Width     0.8179411  -0.3661259    0.9628654</span></span>
<span id="cb223-7"><a href="modeling.html#cb223-7" tabindex="-1"></a><span class="co">#&gt;              Petal.Width</span></span>
<span id="cb223-8"><a href="modeling.html#cb223-8" tabindex="-1"></a><span class="co">#&gt; Sepal.Length   0.8179411</span></span>
<span id="cb223-9"><a href="modeling.html#cb223-9" tabindex="-1"></a><span class="co">#&gt; Sepal.Width   -0.3661259</span></span>
<span id="cb223-10"><a href="modeling.html#cb223-10" tabindex="-1"></a><span class="co">#&gt; Petal.Length   0.9628654</span></span>
<span id="cb223-11"><a href="modeling.html#cb223-11" tabindex="-1"></a><span class="co">#&gt; Petal.Width    1.0000000</span></span></code></pre></div>
</div>
</div>
<div id="examples-wdi" class="section level2" number="20.11">
<h2><span class="header-section-number">20.11</span> Examples: WDI</h2>
<ul>
<li>SP.DYN.LE00.IN: Life expectancy at birth, total (years)</li>
</ul>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="modeling.html#cb224-1" tabindex="-1"></a>wdi_lifeExp <span class="ot">&lt;-</span> <span class="fu">WDI</span>(<span class="at">indicator =</span> <span class="fu">c</span>(<span class="at">lifeExp =</span> <span class="st">&quot;SP.DYN.LE00.IN&quot;</span>))</span></code></pre></div>
<pre><code>#&gt; Rows: 16758 Columns: 5
#&gt; ── Column specification ────────────────────────────────────
#&gt; Delimiter: &quot;,&quot;
#&gt; chr (3): country, iso2c, iso3c
#&gt; dbl (2): year, lifeExp
#&gt; 
#&gt; ℹ Use `spec()` to retrieve the full column specification for this data.
#&gt; ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="modeling.html#cb226-1" tabindex="-1"></a>wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;World&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(lifeExp) <span class="sc">%&gt;%</span></span>
<span id="cb226-2"><a href="modeling.html#cb226-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(year, lifeExp)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb226-3"><a href="modeling.html#cb226-3" tabindex="-1"></a><span class="co">#&gt; `geom_smooth()` using formula = &#39;y ~ x&#39;</span></span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="modeling.html#cb227-1" tabindex="-1"></a>wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> year, .) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb227-2"><a href="modeling.html#cb227-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb227-3"><a href="modeling.html#cb227-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb227-4"><a href="modeling.html#cb227-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = lifeExp ~ year, data = .)</span></span>
<span id="cb227-5"><a href="modeling.html#cb227-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb227-6"><a href="modeling.html#cb227-6" tabindex="-1"></a><span class="co">#&gt; Residuals:</span></span>
<span id="cb227-7"><a href="modeling.html#cb227-7" tabindex="-1"></a><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span id="cb227-8"><a href="modeling.html#cb227-8" tabindex="-1"></a><span class="co">#&gt; -51.173  -7.150   1.741   7.794  18.782 </span></span>
<span id="cb227-9"><a href="modeling.html#cb227-9" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb227-10"><a href="modeling.html#cb227-10" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb227-11"><a href="modeling.html#cb227-11" tabindex="-1"></a><span class="co">#&gt;               Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb227-12"><a href="modeling.html#cb227-12" tabindex="-1"></a><span class="co">#&gt; (Intercept) -5.383e+02  8.583e+00  -62.71   &lt;2e-16 ***</span></span>
<span id="cb227-13"><a href="modeling.html#cb227-13" tabindex="-1"></a><span class="co">#&gt; year         3.027e-01  4.312e-03   70.20   &lt;2e-16 ***</span></span>
<span id="cb227-14"><a href="modeling.html#cb227-14" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb227-15"><a href="modeling.html#cb227-15" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  </span></span>
<span id="cb227-16"><a href="modeling.html#cb227-16" tabindex="-1"></a><span class="co">#&gt; 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb227-17"><a href="modeling.html#cb227-17" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb227-18"><a href="modeling.html#cb227-18" tabindex="-1"></a><span class="co">#&gt; Residual standard error: 9.707 on 15864 degrees of freedom</span></span>
<span id="cb227-19"><a href="modeling.html#cb227-19" tabindex="-1"></a><span class="co">#&gt;   (892 observations deleted due to missingness)</span></span>
<span id="cb227-20"><a href="modeling.html#cb227-20" tabindex="-1"></a><span class="co">#&gt; Multiple R-squared:  0.237,  Adjusted R-squared:  0.237 </span></span>
<span id="cb227-21"><a href="modeling.html#cb227-21" tabindex="-1"></a><span class="co">#&gt; F-statistic:  4928 on 1 and 15864 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div>
<p><span class="math display">\[lifeExp \sim -557.4 + 0.3123 \cdot year\]</span>
Each year, life expectancy at birth increases approximately 0.3123 years. R-squared of this model is 0.2392, and the model explains 24%.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="modeling.html#cb228-1" tabindex="-1"></a>wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;World&quot;</span>, year <span class="sc">&gt;=</span> <span class="dv">1962</span>, year <span class="sc">&lt;=</span> <span class="dv">2019</span>) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(lifeExp) <span class="sc">%&gt;%</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> year, .) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb228-2"><a href="modeling.html#cb228-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb228-3"><a href="modeling.html#cb228-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb228-4"><a href="modeling.html#cb228-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = lifeExp ~ year, data = .)</span></span>
<span id="cb228-5"><a href="modeling.html#cb228-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb228-6"><a href="modeling.html#cb228-6" tabindex="-1"></a><span class="co">#&gt; Residuals:</span></span>
<span id="cb228-7"><a href="modeling.html#cb228-7" tabindex="-1"></a><span class="co">#&gt;      Min       1Q   Median       3Q      Max </span></span>
<span id="cb228-8"><a href="modeling.html#cb228-8" tabindex="-1"></a><span class="co">#&gt; -1.00776 -0.29546 -0.04527  0.37540  0.82117 </span></span>
<span id="cb228-9"><a href="modeling.html#cb228-9" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb228-10"><a href="modeling.html#cb228-10" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb228-11"><a href="modeling.html#cb228-11" tabindex="-1"></a><span class="co">#&gt;               Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb228-12"><a href="modeling.html#cb228-12" tabindex="-1"></a><span class="co">#&gt; (Intercept) -5.537e+02  7.841e+00  -70.62   &lt;2e-16 ***</span></span>
<span id="cb228-13"><a href="modeling.html#cb228-13" tabindex="-1"></a><span class="co">#&gt; year         3.107e-01  3.939e-03   78.89   &lt;2e-16 ***</span></span>
<span id="cb228-14"><a href="modeling.html#cb228-14" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb228-15"><a href="modeling.html#cb228-15" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  </span></span>
<span id="cb228-16"><a href="modeling.html#cb228-16" tabindex="-1"></a><span class="co">#&gt; 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb228-17"><a href="modeling.html#cb228-17" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb228-18"><a href="modeling.html#cb228-18" tabindex="-1"></a><span class="co">#&gt; Residual standard error: 0.5022 on 56 degrees of freedom</span></span>
<span id="cb228-19"><a href="modeling.html#cb228-19" tabindex="-1"></a><span class="co">#&gt; Multiple R-squared:  0.9911, Adjusted R-squared:  0.9909 </span></span>
<span id="cb228-20"><a href="modeling.html#cb228-20" tabindex="-1"></a><span class="co">#&gt; F-statistic:  6224 on 1 and 56 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div>
</div>
<div id="brics" class="section level2" number="20.12">
<h2><span class="header-section-number">20.12</span> BRICs</h2>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="modeling.html#cb229-1" tabindex="-1"></a>mod_brics <span class="ot">&lt;-</span> wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Brazil&quot;</span>, <span class="st">&quot;Russian Federation&quot;</span>, <span class="st">&quot;India&quot;</span>, <span class="st">&quot;China&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(lifeExp) <span class="sc">%&gt;%</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> year, .) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb229-2"><a href="modeling.html#cb229-2" tabindex="-1"></a>mod_brics<span class="sc">$</span>r.squared</span>
<span id="cb229-3"><a href="modeling.html#cb229-3" tabindex="-1"></a><span class="co">#&gt; [1] 0.5666988</span></span></code></pre></div>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="modeling.html#cb230-1" tabindex="-1"></a>wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Brazil&quot;</span>, <span class="st">&quot;Russian Federation&quot;</span>, <span class="st">&quot;India&quot;</span>, <span class="st">&quot;China&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(lifeExp) <span class="sc">%&gt;%</span></span>
<span id="cb230-2"><a href="modeling.html#cb230-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(year, lifeExp)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y<span class="sc">~</span>x, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="modeling.html#cb231-1" tabindex="-1"></a>wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Brazil&quot;</span>, <span class="st">&quot;Russian Federation&quot;</span>, <span class="st">&quot;India&quot;</span>, <span class="st">&quot;China&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(lifeExp) <span class="sc">%&gt;%</span></span>
<span id="cb231-2"><a href="modeling.html#cb231-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(year, lifeExp, <span class="at">color =</span> country)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">shape =</span> country)) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y<span class="sc">~</span>x, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Need to work</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="modeling.html#cb232-1" tabindex="-1"></a>country_model <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb232-2"><a href="modeling.html#cb232-2" tabindex="-1"></a>  <span class="fu">lm</span>(lifeExp <span class="sc">~</span> year, <span class="at">data =</span> df)</span>
<span id="cb232-3"><a href="modeling.html#cb232-3" tabindex="-1"></a>}</span>
<span id="cb232-4"><a href="modeling.html#cb232-4" tabindex="-1"></a></span>
<span id="cb232-5"><a href="modeling.html#cb232-5" tabindex="-1"></a>by_country <span class="ot">&lt;-</span> wdi_lifeExp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Brazil&quot;</span>, <span class="st">&quot;Russian Federation&quot;</span>, <span class="st">&quot;India&quot;</span>, <span class="st">&quot;China&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(lifeExp) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span> <span class="fu">nest</span>()</span>
<span id="cb232-6"><a href="modeling.html#cb232-6" tabindex="-1"></a></span>
<span id="cb232-7"><a href="modeling.html#cb232-7" tabindex="-1"></a>by_country <span class="ot">&lt;-</span> by_country <span class="sc">%&gt;%</span> </span>
<span id="cb232-8"><a href="modeling.html#cb232-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="fu">map</span>(data, country_model))</span>
<span id="cb232-9"><a href="modeling.html#cb232-9" tabindex="-1"></a></span>
<span id="cb232-10"><a href="modeling.html#cb232-10" tabindex="-1"></a>by_country <span class="sc">%&gt;%</span> </span>
<span id="cb232-11"><a href="modeling.html#cb232-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tidy =</span> <span class="fu">map</span>(model, broom<span class="sc">::</span>tidy)) <span class="sc">%&gt;%</span> </span>
<span id="cb232-12"><a href="modeling.html#cb232-12" tabindex="-1"></a>  <span class="fu">unnest</span>(tidy)</span>
<span id="cb232-13"><a href="modeling.html#cb232-13" tabindex="-1"></a></span>
<span id="cb232-14"><a href="modeling.html#cb232-14" tabindex="-1"></a>by_country <span class="sc">%&gt;%</span> </span>
<span id="cb232-15"><a href="modeling.html#cb232-15" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">glance =</span> <span class="fu">map</span>(model, broom<span class="sc">::</span>glance)) <span class="sc">%&gt;%</span> </span>
<span id="cb232-16"><a href="modeling.html#cb232-16" tabindex="-1"></a>  <span class="fu">unnest</span>(glance)</span></code></pre></div>
</div>
<div id="government-expenditure-of-gdp" class="section level2" number="20.13">
<h2><span class="header-section-number">20.13</span> Government Expenditure, (% of GDP)</h2>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="modeling.html#cb233-1" tabindex="-1"></a>wdi_cache <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">&quot;./data/wdi_cache.RData&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="modeling.html#cb234-1" tabindex="-1"></a><span class="fu">WDIsearch</span>(<span class="st">&quot;expenditure&quot;</span>, <span class="st">&quot;name&quot;</span>, <span class="at">cache =</span> wdi_cache) <span class="sc">%&gt;%</span> </span>
<span id="cb234-2"><a href="modeling.html#cb234-2" tabindex="-1"></a>  <span class="fu">inner_join</span>(<span class="fu">WDIsearch</span>(<span class="st">&quot;% of GDP&quot;</span>, <span class="st">&quot;name&quot;</span>, <span class="at">cache =</span> wdi_cache))</span>
<span id="cb234-3"><a href="modeling.html#cb234-3" tabindex="-1"></a><span class="co">#&gt; Joining with `by = join_by(indicator, name)`</span></span>
<span id="cb234-4"><a href="modeling.html#cb234-4" tabindex="-1"></a><span class="co">#&gt;               indicator</span></span>
<span id="cb234-5"><a href="modeling.html#cb234-5" tabindex="-1"></a><span class="co">#&gt; 1    GB.XPD.DEFN.GDP.ZS</span></span>
<span id="cb234-6"><a href="modeling.html#cb234-6" tabindex="-1"></a><span class="co">#&gt; 2     GB.XPD.RSDV.GD.ZS</span></span>
<span id="cb234-7"><a href="modeling.html#cb234-7" tabindex="-1"></a><span class="co">#&gt; 3     GB.XPD.TOTL.GD.ZS</span></span>
<span id="cb234-8"><a href="modeling.html#cb234-8" tabindex="-1"></a><span class="co">#&gt; 4    GB.XPD.TOTL.GDP.ZS</span></span>
<span id="cb234-9"><a href="modeling.html#cb234-9" tabindex="-1"></a><span class="co">#&gt; 5     IE.ICT.TOTL.GD.ZS</span></span>
<span id="cb234-10"><a href="modeling.html#cb234-10" tabindex="-1"></a><span class="co">#&gt; 6     MS.MIL.XPND.GD.ZS</span></span>
<span id="cb234-11"><a href="modeling.html#cb234-11" tabindex="-1"></a><span class="co">#&gt; 7        NE.CON.GOVT.ZS</span></span>
<span id="cb234-12"><a href="modeling.html#cb234-12" tabindex="-1"></a><span class="co">#&gt; 8        NE.CON.PETC.ZS</span></span>
<span id="cb234-13"><a href="modeling.html#cb234-13" tabindex="-1"></a><span class="co">#&gt; 9        NE.CON.PRVT.ZS</span></span>
<span id="cb234-14"><a href="modeling.html#cb234-14" tabindex="-1"></a><span class="co">#&gt; 10       NE.CON.TETC.ZS</span></span>
<span id="cb234-15"><a href="modeling.html#cb234-15" tabindex="-1"></a><span class="co">#&gt; 11       NE.CON.TOTL.ZS</span></span>
<span id="cb234-16"><a href="modeling.html#cb234-16" tabindex="-1"></a><span class="co">#&gt; 12       NE.DAB.TOTL.ZS</span></span>
<span id="cb234-17"><a href="modeling.html#cb234-17" tabindex="-1"></a><span class="co">#&gt; 13    NY.GEN.AEDU.GD.ZS</span></span>
<span id="cb234-18"><a href="modeling.html#cb234-18" tabindex="-1"></a><span class="co">#&gt; 14    SE.XPD.PRIM.PC.ZS</span></span>
<span id="cb234-19"><a href="modeling.html#cb234-19" tabindex="-1"></a><span class="co">#&gt; 15    SE.XPD.SECO.PC.ZS</span></span>
<span id="cb234-20"><a href="modeling.html#cb234-20" tabindex="-1"></a><span class="co">#&gt; 16    SE.XPD.TERT.PC.ZS</span></span>
<span id="cb234-21"><a href="modeling.html#cb234-21" tabindex="-1"></a><span class="co">#&gt; 17    SE.XPD.TOTL.GD.ZS</span></span>
<span id="cb234-22"><a href="modeling.html#cb234-22" tabindex="-1"></a><span class="co">#&gt; 18    SH.XPD.CHEX.GD.ZS</span></span>
<span id="cb234-23"><a href="modeling.html#cb234-23" tabindex="-1"></a><span class="co">#&gt; 19    SH.XPD.GHED.GD.ZS</span></span>
<span id="cb234-24"><a href="modeling.html#cb234-24" tabindex="-1"></a><span class="co">#&gt; 20    SH.XPD.KHEX.GD.ZS</span></span>
<span id="cb234-25"><a href="modeling.html#cb234-25" tabindex="-1"></a><span class="co">#&gt; 21       SH.XPD.PRIV.ZS</span></span>
<span id="cb234-26"><a href="modeling.html#cb234-26" tabindex="-1"></a><span class="co">#&gt; 22       SH.XPD.PUBL.ZS</span></span>
<span id="cb234-27"><a href="modeling.html#cb234-27" tabindex="-1"></a><span class="co">#&gt; 23       SH.XPD.TOTL.ZS</span></span>
<span id="cb234-28"><a href="modeling.html#cb234-28" tabindex="-1"></a><span class="co">#&gt; 24     UIS.XGDP.0.FSGOV</span></span>
<span id="cb234-29"><a href="modeling.html#cb234-29" tabindex="-1"></a><span class="co">#&gt; 25     UIS.XGDP.1.FSGOV</span></span>
<span id="cb234-30"><a href="modeling.html#cb234-30" tabindex="-1"></a><span class="co">#&gt; 26    UIS.XGDP.23.FSGOV</span></span>
<span id="cb234-31"><a href="modeling.html#cb234-31" tabindex="-1"></a><span class="co">#&gt; 27 UIS.XGDP.2T4.V.FSGOV</span></span>
<span id="cb234-32"><a href="modeling.html#cb234-32" tabindex="-1"></a><span class="co">#&gt; 28     UIS.XGDP.4.FSGOV</span></span>
<span id="cb234-33"><a href="modeling.html#cb234-33" tabindex="-1"></a><span class="co">#&gt; 29    UIS.XGDP.56.FSGOV</span></span>
<span id="cb234-34"><a href="modeling.html#cb234-34" tabindex="-1"></a><span class="co">#&gt;                                                                                                        name</span></span>
<span id="cb234-35"><a href="modeling.html#cb234-35" tabindex="-1"></a><span class="co">#&gt; 1                                                                            Defense expenditure (% of GDP)</span></span>
<span id="cb234-36"><a href="modeling.html#cb234-36" tabindex="-1"></a><span class="co">#&gt; 2                                                           Research and development expenditure (% of GDP)</span></span>
<span id="cb234-37"><a href="modeling.html#cb234-37" tabindex="-1"></a><span class="co">#&gt; 3                                                                             Expenditure, total (% of GDP)</span></span>
<span id="cb234-38"><a href="modeling.html#cb234-38" tabindex="-1"></a><span class="co">#&gt; 4                                                                              Total expenditure (% of GDP)</span></span>
<span id="cb234-39"><a href="modeling.html#cb234-39" tabindex="-1"></a><span class="co">#&gt; 5                                           Information and communication technology expenditure (% of GDP)</span></span>
<span id="cb234-40"><a href="modeling.html#cb234-40" tabindex="-1"></a><span class="co">#&gt; 6                                                                           Military expenditure (% of GDP)</span></span>
<span id="cb234-41"><a href="modeling.html#cb234-41" tabindex="-1"></a><span class="co">#&gt; 7                                               General government final consumption expenditure (% of GDP)</span></span>
<span id="cb234-42"><a href="modeling.html#cb234-42" tabindex="-1"></a><span class="co">#&gt; 8                                                  Household final consumption expenditure, etc. (% of GDP)</span></span>
<span id="cb234-43"><a href="modeling.html#cb234-43" tabindex="-1"></a><span class="co">#&gt; 9                                            Households and NPISHs final consumption expenditure (% of GDP)</span></span>
<span id="cb234-44"><a href="modeling.html#cb234-44" tabindex="-1"></a><span class="co">#&gt; 10                                                           Final consumption expenditure, etc. (% of GDP)</span></span>
<span id="cb234-45"><a href="modeling.html#cb234-45" tabindex="-1"></a><span class="co">#&gt; 11                                                                 Final consumption expenditure (% of GDP)</span></span>
<span id="cb234-46"><a href="modeling.html#cb234-46" tabindex="-1"></a><span class="co">#&gt; 12                                                                    Gross national expenditure (% of GDP)</span></span>
<span id="cb234-47"><a href="modeling.html#cb234-47" tabindex="-1"></a><span class="co">#&gt; 13                                                        Genuine savings: education expenditure (% of GDP)</span></span>
<span id="cb234-48"><a href="modeling.html#cb234-48" tabindex="-1"></a><span class="co">#&gt; 14                                        Government expenditure per student, primary (% of GDP per capita)</span></span>
<span id="cb234-49"><a href="modeling.html#cb234-49" tabindex="-1"></a><span class="co">#&gt; 15                                      Government expenditure per student, secondary (% of GDP per capita)</span></span>
<span id="cb234-50"><a href="modeling.html#cb234-50" tabindex="-1"></a><span class="co">#&gt; 16                                       Government expenditure per student, tertiary (% of GDP per capita)</span></span>
<span id="cb234-51"><a href="modeling.html#cb234-51" tabindex="-1"></a><span class="co">#&gt; 17                                                    Government expenditure on education, total (% of GDP)</span></span>
<span id="cb234-52"><a href="modeling.html#cb234-52" tabindex="-1"></a><span class="co">#&gt; 18                                                                    Current health expenditure (% of GDP)</span></span>
<span id="cb234-53"><a href="modeling.html#cb234-53" tabindex="-1"></a><span class="co">#&gt; 19                                                Domestic general government health expenditure (% of GDP)</span></span>
<span id="cb234-54"><a href="modeling.html#cb234-54" tabindex="-1"></a><span class="co">#&gt; 20                                                                    Capital health expenditure (% of GDP)</span></span>
<span id="cb234-55"><a href="modeling.html#cb234-55" tabindex="-1"></a><span class="co">#&gt; 21                                                                   Health expenditure, private (% of GDP)</span></span>
<span id="cb234-56"><a href="modeling.html#cb234-56" tabindex="-1"></a><span class="co">#&gt; 22                                                                    Health expenditure, public (% of GDP)</span></span>
<span id="cb234-57"><a href="modeling.html#cb234-57" tabindex="-1"></a><span class="co">#&gt; 23                                                                     Health expenditure, total (% of GDP)</span></span>
<span id="cb234-58"><a href="modeling.html#cb234-58" tabindex="-1"></a><span class="co">#&gt; 24                                          Government expenditure on pre-primary education as % of GDP (%)</span></span>
<span id="cb234-59"><a href="modeling.html#cb234-59" tabindex="-1"></a><span class="co">#&gt; 25                                              Government expenditure on primary education as % of GDP (%)</span></span>
<span id="cb234-60"><a href="modeling.html#cb234-60" tabindex="-1"></a><span class="co">#&gt; 26                                            Government expenditure on secondary education as % of GDP (%)</span></span>
<span id="cb234-61"><a href="modeling.html#cb234-61" tabindex="-1"></a><span class="co">#&gt; 27 Government expenditure on secondary and post-secondary non-tertiary vocational education as % of GDP (%)</span></span>
<span id="cb234-62"><a href="modeling.html#cb234-62" tabindex="-1"></a><span class="co">#&gt; 28                          Government expenditure on post-secondary non-tertiary education as % of GDP (%)</span></span>
<span id="cb234-63"><a href="modeling.html#cb234-63" tabindex="-1"></a><span class="co">#&gt; 29                                             Government expenditure on tertiary education as % of GDP (%)</span></span></code></pre></div>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="modeling.html#cb235-1" tabindex="-1"></a>wdi_cache<span class="sc">$</span>series <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">&quot;expenditure&quot;</span>, name), <span class="fu">grepl</span>(<span class="st">&quot;% of GDP&quot;</span>, name))</span>
<span id="cb235-2"><a href="modeling.html#cb235-2" tabindex="-1"></a><span class="co">#&gt;               indicator</span></span>
<span id="cb235-3"><a href="modeling.html#cb235-3" tabindex="-1"></a><span class="co">#&gt; 1    GB.XPD.DEFN.GDP.ZS</span></span>
<span id="cb235-4"><a href="modeling.html#cb235-4" tabindex="-1"></a><span class="co">#&gt; 2     GB.XPD.RSDV.GD.ZS</span></span>
<span id="cb235-5"><a href="modeling.html#cb235-5" tabindex="-1"></a><span class="co">#&gt; 3    GB.XPD.TOTL.GDP.ZS</span></span>
<span id="cb235-6"><a href="modeling.html#cb235-6" tabindex="-1"></a><span class="co">#&gt; 4     IE.ICT.TOTL.GD.ZS</span></span>
<span id="cb235-7"><a href="modeling.html#cb235-7" tabindex="-1"></a><span class="co">#&gt; 5     MS.MIL.XPND.GD.ZS</span></span>
<span id="cb235-8"><a href="modeling.html#cb235-8" tabindex="-1"></a><span class="co">#&gt; 6        NE.CON.GOVT.ZS</span></span>
<span id="cb235-9"><a href="modeling.html#cb235-9" tabindex="-1"></a><span class="co">#&gt; 7        NE.CON.PETC.ZS</span></span>
<span id="cb235-10"><a href="modeling.html#cb235-10" tabindex="-1"></a><span class="co">#&gt; 8        NE.CON.PRVT.ZS</span></span>
<span id="cb235-11"><a href="modeling.html#cb235-11" tabindex="-1"></a><span class="co">#&gt; 9        NE.CON.TETC.ZS</span></span>
<span id="cb235-12"><a href="modeling.html#cb235-12" tabindex="-1"></a><span class="co">#&gt; 10       NE.CON.TOTL.ZS</span></span>
<span id="cb235-13"><a href="modeling.html#cb235-13" tabindex="-1"></a><span class="co">#&gt; 11       NE.DAB.TOTL.ZS</span></span>
<span id="cb235-14"><a href="modeling.html#cb235-14" tabindex="-1"></a><span class="co">#&gt; 12    NY.GEN.AEDU.GD.ZS</span></span>
<span id="cb235-15"><a href="modeling.html#cb235-15" tabindex="-1"></a><span class="co">#&gt; 13    SE.XPD.PRIM.PC.ZS</span></span>
<span id="cb235-16"><a href="modeling.html#cb235-16" tabindex="-1"></a><span class="co">#&gt; 14    SE.XPD.SECO.PC.ZS</span></span>
<span id="cb235-17"><a href="modeling.html#cb235-17" tabindex="-1"></a><span class="co">#&gt; 15    SE.XPD.TERT.PC.ZS</span></span>
<span id="cb235-18"><a href="modeling.html#cb235-18" tabindex="-1"></a><span class="co">#&gt; 16    SE.XPD.TOTL.GD.ZS</span></span>
<span id="cb235-19"><a href="modeling.html#cb235-19" tabindex="-1"></a><span class="co">#&gt; 17    SH.XPD.CHEX.GD.ZS</span></span>
<span id="cb235-20"><a href="modeling.html#cb235-20" tabindex="-1"></a><span class="co">#&gt; 18    SH.XPD.GHED.GD.ZS</span></span>
<span id="cb235-21"><a href="modeling.html#cb235-21" tabindex="-1"></a><span class="co">#&gt; 19    SH.XPD.KHEX.GD.ZS</span></span>
<span id="cb235-22"><a href="modeling.html#cb235-22" tabindex="-1"></a><span class="co">#&gt; 20       SH.XPD.PRIV.ZS</span></span>
<span id="cb235-23"><a href="modeling.html#cb235-23" tabindex="-1"></a><span class="co">#&gt; 21       SH.XPD.PUBL.ZS</span></span>
<span id="cb235-24"><a href="modeling.html#cb235-24" tabindex="-1"></a><span class="co">#&gt; 22       SH.XPD.TOTL.ZS</span></span>
<span id="cb235-25"><a href="modeling.html#cb235-25" tabindex="-1"></a><span class="co">#&gt; 23     UIS.XGDP.0.FSGOV</span></span>
<span id="cb235-26"><a href="modeling.html#cb235-26" tabindex="-1"></a><span class="co">#&gt; 24     UIS.XGDP.1.FSGOV</span></span>
<span id="cb235-27"><a href="modeling.html#cb235-27" tabindex="-1"></a><span class="co">#&gt; 25    UIS.XGDP.23.FSGOV</span></span>
<span id="cb235-28"><a href="modeling.html#cb235-28" tabindex="-1"></a><span class="co">#&gt; 26 UIS.XGDP.2T4.V.FSGOV</span></span>
<span id="cb235-29"><a href="modeling.html#cb235-29" tabindex="-1"></a><span class="co">#&gt; 27     UIS.XGDP.4.FSGOV</span></span>
<span id="cb235-30"><a href="modeling.html#cb235-30" tabindex="-1"></a><span class="co">#&gt; 28    UIS.XGDP.56.FSGOV</span></span>
<span id="cb235-31"><a href="modeling.html#cb235-31" tabindex="-1"></a><span class="co">#&gt;                                                                                                        name</span></span>
<span id="cb235-32"><a href="modeling.html#cb235-32" tabindex="-1"></a><span class="co">#&gt; 1                                                                            Defense expenditure (% of GDP)</span></span>
<span id="cb235-33"><a href="modeling.html#cb235-33" tabindex="-1"></a><span class="co">#&gt; 2                                                           Research and development expenditure (% of GDP)</span></span>
<span id="cb235-34"><a href="modeling.html#cb235-34" tabindex="-1"></a><span class="co">#&gt; 3                                                                              Total expenditure (% of GDP)</span></span>
<span id="cb235-35"><a href="modeling.html#cb235-35" tabindex="-1"></a><span class="co">#&gt; 4                                           Information and communication technology expenditure (% of GDP)</span></span>
<span id="cb235-36"><a href="modeling.html#cb235-36" tabindex="-1"></a><span class="co">#&gt; 5                                                                           Military expenditure (% of GDP)</span></span>
<span id="cb235-37"><a href="modeling.html#cb235-37" tabindex="-1"></a><span class="co">#&gt; 6                                               General government final consumption expenditure (% of GDP)</span></span>
<span id="cb235-38"><a href="modeling.html#cb235-38" tabindex="-1"></a><span class="co">#&gt; 7                                                  Household final consumption expenditure, etc. (% of GDP)</span></span>
<span id="cb235-39"><a href="modeling.html#cb235-39" tabindex="-1"></a><span class="co">#&gt; 8                                            Households and NPISHs final consumption expenditure (% of GDP)</span></span>
<span id="cb235-40"><a href="modeling.html#cb235-40" tabindex="-1"></a><span class="co">#&gt; 9                                                            Final consumption expenditure, etc. (% of GDP)</span></span>
<span id="cb235-41"><a href="modeling.html#cb235-41" tabindex="-1"></a><span class="co">#&gt; 10                                                                 Final consumption expenditure (% of GDP)</span></span>
<span id="cb235-42"><a href="modeling.html#cb235-42" tabindex="-1"></a><span class="co">#&gt; 11                                                                    Gross national expenditure (% of GDP)</span></span>
<span id="cb235-43"><a href="modeling.html#cb235-43" tabindex="-1"></a><span class="co">#&gt; 12                                                        Genuine savings: education expenditure (% of GDP)</span></span>
<span id="cb235-44"><a href="modeling.html#cb235-44" tabindex="-1"></a><span class="co">#&gt; 13                                        Government expenditure per student, primary (% of GDP per capita)</span></span>
<span id="cb235-45"><a href="modeling.html#cb235-45" tabindex="-1"></a><span class="co">#&gt; 14                                      Government expenditure per student, secondary (% of GDP per capita)</span></span>
<span id="cb235-46"><a href="modeling.html#cb235-46" tabindex="-1"></a><span class="co">#&gt; 15                                       Government expenditure per student, tertiary (% of GDP per capita)</span></span>
<span id="cb235-47"><a href="modeling.html#cb235-47" tabindex="-1"></a><span class="co">#&gt; 16                                                    Government expenditure on education, total (% of GDP)</span></span>
<span id="cb235-48"><a href="modeling.html#cb235-48" tabindex="-1"></a><span class="co">#&gt; 17                                                                    Current health expenditure (% of GDP)</span></span>
<span id="cb235-49"><a href="modeling.html#cb235-49" tabindex="-1"></a><span class="co">#&gt; 18                                                Domestic general government health expenditure (% of GDP)</span></span>
<span id="cb235-50"><a href="modeling.html#cb235-50" tabindex="-1"></a><span class="co">#&gt; 19                                                                    Capital health expenditure (% of GDP)</span></span>
<span id="cb235-51"><a href="modeling.html#cb235-51" tabindex="-1"></a><span class="co">#&gt; 20                                                                   Health expenditure, private (% of GDP)</span></span>
<span id="cb235-52"><a href="modeling.html#cb235-52" tabindex="-1"></a><span class="co">#&gt; 21                                                                    Health expenditure, public (% of GDP)</span></span>
<span id="cb235-53"><a href="modeling.html#cb235-53" tabindex="-1"></a><span class="co">#&gt; 22                                                                     Health expenditure, total (% of GDP)</span></span>
<span id="cb235-54"><a href="modeling.html#cb235-54" tabindex="-1"></a><span class="co">#&gt; 23                                          Government expenditure on pre-primary education as % of GDP (%)</span></span>
<span id="cb235-55"><a href="modeling.html#cb235-55" tabindex="-1"></a><span class="co">#&gt; 24                                              Government expenditure on primary education as % of GDP (%)</span></span>
<span id="cb235-56"><a href="modeling.html#cb235-56" tabindex="-1"></a><span class="co">#&gt; 25                                            Government expenditure on secondary education as % of GDP (%)</span></span>
<span id="cb235-57"><a href="modeling.html#cb235-57" tabindex="-1"></a><span class="co">#&gt; 26 Government expenditure on secondary and post-secondary non-tertiary vocational education as % of GDP (%)</span></span>
<span id="cb235-58"><a href="modeling.html#cb235-58" tabindex="-1"></a><span class="co">#&gt; 27                          Government expenditure on post-secondary non-tertiary education as % of GDP (%)</span></span>
<span id="cb235-59"><a href="modeling.html#cb235-59" tabindex="-1"></a><span class="co">#&gt; 28                                             Government expenditure on tertiary education as % of GDP (%)</span></span>
<span id="cb235-60"><a href="modeling.html#cb235-60" tabindex="-1"></a><span class="co">#&gt;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description</span></span>
<span id="cb235-61"><a href="modeling.html#cb235-61" tabindex="-1"></a><span class="co">#&gt; 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </span></span>
<span id="cb235-62"><a href="modeling.html#cb235-62" tabindex="-1"></a><span class="co">#&gt; 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Gross domestic expenditures on research and development (R&amp;D), expressed as a percent of GDP. They include both capital and current expenditures in the four main sectors: Business enterprise, Government, Higher education and Private non-profit. R&amp;D covers basic research, applied research, and experimental development.</span></span>
<span id="cb235-63"><a href="modeling.html#cb235-63" tabindex="-1"></a><span class="co">#&gt; 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </span></span>
<span id="cb235-64"><a href="modeling.html#cb235-64" tabindex="-1"></a><span class="co">#&gt; 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Information and communications technology expenditures include computer hardware (computers, storage devices, printers, and other peripherals); computer software (operating systems, programming tools, utilities, applications, and internal software development); computer services (information technology consulting, computer and network systems integration, Web hosting, data processing services, and other services); and communications services (voice and data communications services) and wired and wireless communications equipment.</span></span>
<span id="cb235-65"><a href="modeling.html#cb235-65" tabindex="-1"></a><span class="co">#&gt; 5  Military expenditures data from SIPRI are derived from the NATO definition, which includes all current and capital expenditures on the armed forces, including peacekeeping forces; defense ministries and other government agencies engaged in defense projects; paramilitary forces, if these are judged to be trained and equipped for military operations; and military space activities. Such expenditures include military and civil personnel, including retirement pensions of military personnel and social services for personnel; operation and maintenance; procurement; military research and development; and military aid (in the military expenditures of the donor country). Excluded are civil defense and current expenditures for previous military activities, such as for veterans&#39; benefits, demobilization, conversion, and destruction of weapons. This definition cannot be applied for all countries, however, since that would require much more detailed information than is available about what is included in military budgets and off-budget military expenditure items. (For example, military budgets might or might not cover civil defense, reserves and auxiliary forces, police and paramilitary forces, dual-purpose forces such as military and civilian police, military grants in kind, pensions for military personnel, and social security contributions paid by one part of government to another.)</span></span>
<span id="cb235-66"><a href="modeling.html#cb235-66" tabindex="-1"></a><span class="co">#&gt; 6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               General government final consumption expenditure (formerly general government consumption) includes all government current expenditures for purchases of goods and services (including compensation of employees). It also includes most expenditures on national defense and security, but excludes government military expenditures that are part of government capital formation.</span></span>
<span id="cb235-67"><a href="modeling.html#cb235-67" tabindex="-1"></a><span class="co">#&gt; 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Household final consumption expenditure (formerly private consumption) is the market value of all goods and services, including durable products (such as cars, washing machines, and home computers), purchased by households. It excludes purchases of dwellings but includes imputed rent for owner-occupied dwellings. It also includes payments and fees to governments to obtain permits and licenses. Here, household consumption expenditure includes the expenditures of nonprofit institutions serving households, even when reported separately by the country. This item also includes any statistical discrepancy in the use of resources relative to the supply of resources.</span></span>
<span id="cb235-68"><a href="modeling.html#cb235-68" tabindex="-1"></a><span class="co">#&gt; 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Household final consumption expenditure (formerly private consumption) is the market value of all goods and services, including durable products (such as cars, washing machines, and home computers), purchased by households. It excludes purchases of dwellings but includes imputed rent for owner-occupied dwellings. It also includes payments and fees to governments to obtain permits and licenses. Here, household consumption expenditure includes the expenditures of nonprofit institutions serving households, even when reported separately by the country. This item also includes any statistical discrepancy in the use of resources relative to the supply of resources.</span></span>
<span id="cb235-69"><a href="modeling.html#cb235-69" tabindex="-1"></a><span class="co">#&gt; 9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Final consumption expenditure (formerly total consumption) is the sum of household final consumption expenditure (private consumption) and general government final consumption expenditure (general government consumption). This estimate includes any statistical discrepancy in the use of resources relative to the supply of resources.</span></span>
<span id="cb235-70"><a href="modeling.html#cb235-70" tabindex="-1"></a><span class="co">#&gt; 10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Final consumption expenditure (formerly total consumption) is the sum of household final consumption expenditure (private consumption) and general government final consumption expenditure (general government consumption). This estimate includes any statistical discrepancy in the use of resources relative to the supply of resources.</span></span>
<span id="cb235-71"><a href="modeling.html#cb235-71" tabindex="-1"></a><span class="co">#&gt; 11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Gross national expenditure (formerly domestic absorption) is the sum of household final consumption expenditure (formerly private consumption), general government final consumption expenditure (formerly general government consumption), and gross capital formation (formerly gross domestic investment).</span></span>
<span id="cb235-72"><a href="modeling.html#cb235-72" tabindex="-1"></a><span class="co">#&gt; 12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span></span>
<span id="cb235-73"><a href="modeling.html#cb235-73" tabindex="-1"></a><span class="co">#&gt; 13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Government expenditure per student is the average general government expenditure (current, capital, and transfers) per student in the given level of education, expressed as a percentage of GDP per capita.</span></span>
<span id="cb235-74"><a href="modeling.html#cb235-74" tabindex="-1"></a><span class="co">#&gt; 14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Government expenditure per student is the average general government expenditure (current, capital, and transfers) per student in the given level of education, expressed as a percentage of GDP per capita.</span></span>
<span id="cb235-75"><a href="modeling.html#cb235-75" tabindex="-1"></a><span class="co">#&gt; 15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Government expenditure per student is the average general government expenditure (current, capital, and transfers) per student in the given level of education, expressed as a percentage of GDP per capita.</span></span>
<span id="cb235-76"><a href="modeling.html#cb235-76" tabindex="-1"></a><span class="co">#&gt; 16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            General government expenditure on education (current, capital, and transfers) is expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. General government usually refers to local, regional and central governments.</span></span>
<span id="cb235-77"><a href="modeling.html#cb235-77" tabindex="-1"></a><span class="co">#&gt; 17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Level of current health expenditure expressed as a percentage of GDP.  Estimates of current health expenditures include healthcare goods and services consumed during each year. This indicator does not include capital health expenditures such as buildings, machinery, IT and stocks of vaccines for emergency or outbreaks.</span></span>
<span id="cb235-78"><a href="modeling.html#cb235-78" tabindex="-1"></a><span class="co">#&gt; 18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Public expenditure on health from domestic sources as a share of the economy as measured by GDP.</span></span>
<span id="cb235-79"><a href="modeling.html#cb235-79" tabindex="-1"></a><span class="co">#&gt; 19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Level of capital investments on health expressed as a percentage of GDP.  Capital health investments include health infrastructure (buildings, machinery, IT) and stocks of vaccines for emergency or outbreaks.</span></span>
<span id="cb235-80"><a href="modeling.html#cb235-80" tabindex="-1"></a><span class="co">#&gt; 20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Private health expenditure includes direct household (out-of-pocket) spending, private insurance, charitable donations, and direct service payments by private corporations.</span></span>
<span id="cb235-81"><a href="modeling.html#cb235-81" tabindex="-1"></a><span class="co">#&gt; 21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Public health expenditure consists of recurrent and capital spending from government (central and local) budgets, external borrowings and grants (including donations from international agencies and nongovernmental organizations), and social (or compulsory) health insurance funds.</span></span>
<span id="cb235-82"><a href="modeling.html#cb235-82" tabindex="-1"></a><span class="co">#&gt; 22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Total health expenditure is the sum of public and private health expenditure. It covers the provision of health services (preventive and curative), family planning activities, nutrition activities, and emergency aid designated for health but does not include provision of water and sanitation.</span></span>
<span id="cb235-83"><a href="modeling.html#cb235-83" tabindex="-1"></a><span class="co">#&gt; 23                                                                                                                                                                                         Total general (local, regional and central) government expenditure on pre-primary education (current, capital, and transfers), expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. Divide total government expenditure for a given level of education (ex. primary, secondary, or all levels combined) by the GDP, and multiply by 100. A higher percentage of GDP spent on education shows a higher government priority for education, but also a higher capacity of the government to raise revenues for public spending, in relation to the size of the country&#39;s economy. When interpreting this indicator however, one should keep in mind in some countries, the private sector and/or households may fund a higher proportion of total funding for education, thus making government expenditure appear lower than in other countries. Limitations: In some instances data on total public expenditure on education refers only to the Ministry of Education, excluding other ministries which may also spend a part of their budget on educational activities. For more information, consult the UNESCO Institute of Statistics website: http://www.uis.unesco.org/Education/</span></span>
<span id="cb235-84"><a href="modeling.html#cb235-84" tabindex="-1"></a><span class="co">#&gt; 24                                                                                                                                                                                             Total general (local, regional and central) government expenditure on primary education (current, capital, and transfers), expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. Divide total government expenditure for a given level of education (ex. primary, secondary, or all levels combined) by the GDP, and multiply by 100. A higher percentage of GDP spent on education shows a higher government priority for education, but also a higher capacity of the government to raise revenues for public spending, in relation to the size of the country&#39;s economy. When interpreting this indicator however, one should keep in mind in some countries, the private sector and/or households may fund a higher proportion of total funding for education, thus making government expenditure appear lower than in other countries. Limitations: In some instances data on total public expenditure on education refers only to the Ministry of Education, excluding other ministries which may also spend a part of their budget on educational activities. For more information, consult the UNESCO Institute of Statistics website: http://www.uis.unesco.org/Education/</span></span>
<span id="cb235-85"><a href="modeling.html#cb235-85" tabindex="-1"></a><span class="co">#&gt; 25                                                                                                                                                                                           Total general (local, regional and central) government expenditure on secondary education (current, capital, and transfers), expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. Divide total government expenditure for a given level of education (ex. primary, secondary, or all levels combined) by the GDP, and multiply by 100. A higher percentage of GDP spent on education shows a higher government priority for education, but also a higher capacity of the government to raise revenues for public spending, in relation to the size of the country&#39;s economy. When interpreting this indicator however, one should keep in mind in some countries, the private sector and/or households may fund a higher proportion of total funding for education, thus making government expenditure appear lower than in other countries. Limitations: In some instances data on total public expenditure on education refers only to the Ministry of Education, excluding other ministries which may also spend a part of their budget on educational activities. For more information, consult the UNESCO Institute of Statistics website: http://www.uis.unesco.org/Education/</span></span>
<span id="cb235-86"><a href="modeling.html#cb235-86" tabindex="-1"></a><span class="co">#&gt; 26                                                                                                                                                Total general (local, regional and central) government expenditure on secondary and post-secondary non-tertiary vocational education (current, capital, and transfers), expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. Divide total government expenditure for a given level of education (ex. primary, secondary, or all levels combined) by the GDP, and multiply by 100. A higher percentage of GDP spent on education shows a higher government priority for education, but also a higher capacity of the government to raise revenues for public spending, in relation to the size of the country&#39;s economy. When interpreting this indicator however, one should keep in mind in some countries, the private sector and/or households may fund a higher proportion of total funding for education, thus making government expenditure appear lower than in other countries. Limitations: In some instances data on total public expenditure on education refers only to the Ministry of Education, excluding other ministries which may also spend a part of their budget on educational activities. For more information, consult the UNESCO Institute of Statistics website: http://www.uis.unesco.org/Education/</span></span>
<span id="cb235-87"><a href="modeling.html#cb235-87" tabindex="-1"></a><span class="co">#&gt; 27                                                                                                                                                                         Total general (local, regional and central) government expenditure on post-secondary non-tertiary education (current, capital, and transfers), expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. Divide total government expenditure for a given level of education (ex. primary, secondary, or all levels combined) by the GDP, and multiply by 100. A higher percentage of GDP spent on education shows a higher government priority for education, but also a higher capacity of the government to raise revenues for public spending, in relation to the size of the country&#39;s economy. When interpreting this indicator however, one should keep in mind in some countries, the private sector and/or households may fund a higher proportion of total funding for education, thus making government expenditure appear lower than in other countries. Limitations: In some instances data on total public expenditure on education refers only to the Ministry of Education, excluding other ministries which may also spend a part of their budget on educational activities. For more information, consult the UNESCO Institute of Statistics website: http://www.uis.unesco.org/Education/</span></span>
<span id="cb235-88"><a href="modeling.html#cb235-88" tabindex="-1"></a><span class="co">#&gt; 28                                                                                                                                                                                            Total general (local, regional and central) government expenditure on tertiary education (current, capital, and transfers), expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. Divide total government expenditure for a given level of education (ex. primary, secondary, or all levels combined) by the GDP, and multiply by 100. A higher percentage of GDP spent on education shows a higher government priority for education, but also a higher capacity of the government to raise revenues for public spending, in relation to the size of the country&#39;s economy. When interpreting this indicator however, one should keep in mind in some countries, the private sector and/or households may fund a higher proportion of total funding for education, thus making government expenditure appear lower than in other countries. Limitations: In some instances data on total public expenditure on education refers only to the Ministry of Education, excluding other ministries which may also spend a part of their budget on educational activities. For more information, consult the UNESCO Institute of Statistics website: http://www.uis.unesco.org/Education/</span></span>
<span id="cb235-89"><a href="modeling.html#cb235-89" tabindex="-1"></a><span class="co">#&gt;                                sourceDatabase</span></span>
<span id="cb235-90"><a href="modeling.html#cb235-90" tabindex="-1"></a><span class="co">#&gt; 1                       WDI Database Archives</span></span>
<span id="cb235-91"><a href="modeling.html#cb235-91" tabindex="-1"></a><span class="co">#&gt; 2                World Development Indicators</span></span>
<span id="cb235-92"><a href="modeling.html#cb235-92" tabindex="-1"></a><span class="co">#&gt; 3                       WDI Database Archives</span></span>
<span id="cb235-93"><a href="modeling.html#cb235-93" tabindex="-1"></a><span class="co">#&gt; 4               Africa Development Indicators</span></span>
<span id="cb235-94"><a href="modeling.html#cb235-94" tabindex="-1"></a><span class="co">#&gt; 5                World Development Indicators</span></span>
<span id="cb235-95"><a href="modeling.html#cb235-95" tabindex="-1"></a><span class="co">#&gt; 6                World Development Indicators</span></span>
<span id="cb235-96"><a href="modeling.html#cb235-96" tabindex="-1"></a><span class="co">#&gt; 7                       WDI Database Archives</span></span>
<span id="cb235-97"><a href="modeling.html#cb235-97" tabindex="-1"></a><span class="co">#&gt; 8                World Development Indicators</span></span>
<span id="cb235-98"><a href="modeling.html#cb235-98" tabindex="-1"></a><span class="co">#&gt; 9                       WDI Database Archives</span></span>
<span id="cb235-99"><a href="modeling.html#cb235-99" tabindex="-1"></a><span class="co">#&gt; 10               World Development Indicators</span></span>
<span id="cb235-100"><a href="modeling.html#cb235-100" tabindex="-1"></a><span class="co">#&gt; 11               World Development Indicators</span></span>
<span id="cb235-101"><a href="modeling.html#cb235-101" tabindex="-1"></a><span class="co">#&gt; 12                      WDI Database Archives</span></span>
<span id="cb235-102"><a href="modeling.html#cb235-102" tabindex="-1"></a><span class="co">#&gt; 13               World Development Indicators</span></span>
<span id="cb235-103"><a href="modeling.html#cb235-103" tabindex="-1"></a><span class="co">#&gt; 14               World Development Indicators</span></span>
<span id="cb235-104"><a href="modeling.html#cb235-104" tabindex="-1"></a><span class="co">#&gt; 15               World Development Indicators</span></span>
<span id="cb235-105"><a href="modeling.html#cb235-105" tabindex="-1"></a><span class="co">#&gt; 16               World Development Indicators</span></span>
<span id="cb235-106"><a href="modeling.html#cb235-106" tabindex="-1"></a><span class="co">#&gt; 17               World Development Indicators</span></span>
<span id="cb235-107"><a href="modeling.html#cb235-107" tabindex="-1"></a><span class="co">#&gt; 18               World Development Indicators</span></span>
<span id="cb235-108"><a href="modeling.html#cb235-108" tabindex="-1"></a><span class="co">#&gt; 19 Health Nutrition and Population Statistics</span></span>
<span id="cb235-109"><a href="modeling.html#cb235-109" tabindex="-1"></a><span class="co">#&gt; 20                      WDI Database Archives</span></span>
<span id="cb235-110"><a href="modeling.html#cb235-110" tabindex="-1"></a><span class="co">#&gt; 21                      WDI Database Archives</span></span>
<span id="cb235-111"><a href="modeling.html#cb235-111" tabindex="-1"></a><span class="co">#&gt; 22                      WDI Database Archives</span></span>
<span id="cb235-112"><a href="modeling.html#cb235-112" tabindex="-1"></a><span class="co">#&gt; 23                       Education Statistics</span></span>
<span id="cb235-113"><a href="modeling.html#cb235-113" tabindex="-1"></a><span class="co">#&gt; 24                       Education Statistics</span></span>
<span id="cb235-114"><a href="modeling.html#cb235-114" tabindex="-1"></a><span class="co">#&gt; 25                       Education Statistics</span></span>
<span id="cb235-115"><a href="modeling.html#cb235-115" tabindex="-1"></a><span class="co">#&gt; 26                       Education Statistics</span></span>
<span id="cb235-116"><a href="modeling.html#cb235-116" tabindex="-1"></a><span class="co">#&gt; 27                       Education Statistics</span></span>
<span id="cb235-117"><a href="modeling.html#cb235-117" tabindex="-1"></a><span class="co">#&gt; 28                       Education Statistics</span></span>
<span id="cb235-118"><a href="modeling.html#cb235-118" tabindex="-1"></a><span class="co">#&gt;                                                                                                                               sourceOrganization</span></span>
<span id="cb235-119"><a href="modeling.html#cb235-119" tabindex="-1"></a><span class="co">#&gt; 1                                                                                                                                               </span></span>
<span id="cb235-120"><a href="modeling.html#cb235-120" tabindex="-1"></a><span class="co">#&gt; 2  UNESCO Institute for Statistics (UIS). UIS.Stat Bulk Data Download Service. Accessed October 24, 2022. https://apiportal.uis.unesco.org/bdds.</span></span>
<span id="cb235-121"><a href="modeling.html#cb235-121" tabindex="-1"></a><span class="co">#&gt; 3                                                                                                                                               </span></span>
<span id="cb235-122"><a href="modeling.html#cb235-122" tabindex="-1"></a><span class="co">#&gt; 4                   World Information Technology and Services Alliance, Digital Planet: The Global Information Economy, and Global Insight, Inc.</span></span>
<span id="cb235-123"><a href="modeling.html#cb235-123" tabindex="-1"></a><span class="co">#&gt; 5                         Stockholm International Peace Research Institute (SIPRI), Yearbook: Armaments, Disarmament and International Security.</span></span>
<span id="cb235-124"><a href="modeling.html#cb235-124" tabindex="-1"></a><span class="co">#&gt; 6                                                                      World Bank national accounts data, and OECD National Accounts data files.</span></span>
<span id="cb235-125"><a href="modeling.html#cb235-125" tabindex="-1"></a><span class="co">#&gt; 7                                                                      World Bank national accounts data, and OECD National Accounts data files.</span></span>
<span id="cb235-126"><a href="modeling.html#cb235-126" tabindex="-1"></a><span class="co">#&gt; 8                                                                      World Bank national accounts data, and OECD National Accounts data files.</span></span>
<span id="cb235-127"><a href="modeling.html#cb235-127" tabindex="-1"></a><span class="co">#&gt; 9                                                                      World Bank national accounts data, and OECD National Accounts data files.</span></span>
<span id="cb235-128"><a href="modeling.html#cb235-128" tabindex="-1"></a><span class="co">#&gt; 10                                                                     World Bank national accounts data, and OECD National Accounts data files.</span></span>
<span id="cb235-129"><a href="modeling.html#cb235-129" tabindex="-1"></a><span class="co">#&gt; 11                                                                     World Bank national accounts data, and OECD National Accounts data files.</span></span>
<span id="cb235-130"><a href="modeling.html#cb235-130" tabindex="-1"></a><span class="co">#&gt; 12                                                                                                                                              </span></span>
<span id="cb235-131"><a href="modeling.html#cb235-131" tabindex="-1"></a><span class="co">#&gt; 13                                                           UNESCO Institute for Statistics (http://uis.unesco.org/). Data as of February 2020.</span></span>
<span id="cb235-132"><a href="modeling.html#cb235-132" tabindex="-1"></a><span class="co">#&gt; 14                                                           UNESCO Institute for Statistics (http://uis.unesco.org/). Data as of February 2020.</span></span>
<span id="cb235-133"><a href="modeling.html#cb235-133" tabindex="-1"></a><span class="co">#&gt; 15                                                           UNESCO Institute for Statistics (http://uis.unesco.org/). Data as of February 2020.</span></span>
<span id="cb235-134"><a href="modeling.html#cb235-134" tabindex="-1"></a><span class="co">#&gt; 16 UNESCO Institute for Statistics (UIS). UIS.Stat Bulk Data Download Service. Accessed October 24, 2022. https://apiportal.uis.unesco.org/bdds.</span></span>
<span id="cb235-135"><a href="modeling.html#cb235-135" tabindex="-1"></a><span class="co">#&gt; 17  World Health Organization Global Health Expenditure database (http://apps.who.int/nha/database). The data was retrieved on January 30, 2022.</span></span>
<span id="cb235-136"><a href="modeling.html#cb235-136" tabindex="-1"></a><span class="co">#&gt; 18  World Health Organization Global Health Expenditure database (http://apps.who.int/nha/database). The data was retrieved on January 30, 2022.</span></span>
<span id="cb235-137"><a href="modeling.html#cb235-137" tabindex="-1"></a><span class="co">#&gt; 19  World Health Organization Global Health Expenditure database (http://apps.who.int/nha/database). The data was retrieved on January 30, 2022.</span></span>
<span id="cb235-138"><a href="modeling.html#cb235-138" tabindex="-1"></a><span class="co">#&gt; 20              World Health Organization Global Health Expenditure database (see http://apps.who.int/nha/database for the most recent updates).</span></span>
<span id="cb235-139"><a href="modeling.html#cb235-139" tabindex="-1"></a><span class="co">#&gt; 21              World Health Organization Global Health Expenditure database (see http://apps.who.int/nha/database for the most recent updates).</span></span>
<span id="cb235-140"><a href="modeling.html#cb235-140" tabindex="-1"></a><span class="co">#&gt; 22              World Health Organization Global Health Expenditure database (see http://apps.who.int/nha/database for the most recent updates).</span></span>
<span id="cb235-141"><a href="modeling.html#cb235-141" tabindex="-1"></a><span class="co">#&gt; 23                                                                                                               UNESCO Institute for Statistics</span></span>
<span id="cb235-142"><a href="modeling.html#cb235-142" tabindex="-1"></a><span class="co">#&gt; 24                                                                                                               UNESCO Institute for Statistics</span></span>
<span id="cb235-143"><a href="modeling.html#cb235-143" tabindex="-1"></a><span class="co">#&gt; 25                                                                                                               UNESCO Institute for Statistics</span></span>
<span id="cb235-144"><a href="modeling.html#cb235-144" tabindex="-1"></a><span class="co">#&gt; 26                                                                                                               UNESCO Institute for Statistics</span></span>
<span id="cb235-145"><a href="modeling.html#cb235-145" tabindex="-1"></a><span class="co">#&gt; 27                                                                                                               UNESCO Institute for Statistics</span></span>
<span id="cb235-146"><a href="modeling.html#cb235-146" tabindex="-1"></a><span class="co">#&gt; 28                                                                                                               UNESCO Institute for Statistics</span></span></code></pre></div>
<ul>
<li><p>NY.GDP.PCAP.KD: GDP per capita (constant 2015 US$)</p></li>
<li><p>SP.DYN.LE00.IN: Life expectancy at birth, total (years)</p></li>
<li><p>SP.POP.TOTL: Population, total</p></li>
<li><p>GB.XPD.RSDV.GD.ZS: Research and development expenditure (% of GDP) - 2</p></li>
<li><p>MS.MIL.XPND.GD.ZS: Military expenditure (% of GDP) - 6</p></li>
<li><p>SE.XPD.TOTL.GD.ZS: Government expenditure on education, total (% of GDP)</p></li>
</ul>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="modeling.html#cb236-1" tabindex="-1"></a>wdi_world <span class="ot">&lt;-</span> <span class="fu">WDI</span>(<span class="at">country =</span> <span class="st">&quot;all&quot;</span>, <span class="at">indicator =</span> <span class="fu">c</span>(<span class="at">gdpPcap =</span> <span class="st">&quot;NY.GDP.PCAP.KD&quot;</span>, <span class="at">lifeExp =</span> <span class="st">&quot;SP.DYN.LE00.IN&quot;</span>, <span class="at">pop =</span> <span class="st">&quot;SP.POP.TOTL&quot;</span>, <span class="at">research =</span> <span class="st">&quot;GB.XPD.RSDV.GD.ZS&quot;</span>, <span class="at">military =</span> <span class="st">&quot;MS.MIL.XPND.GD.ZS&quot;</span>, <span class="at">education =</span> <span class="st">&quot;SE.XPD.TOTL.GD.ZS&quot;</span>), <span class="dv">1990</span>, <span class="at">extra =</span> <span class="cn">TRUE</span>, <span class="at">cache =</span> wdi_cache)</span></code></pre></div>
<pre><code>#&gt; Rows: 8778 Columns: 18
#&gt; ── Column specification ────────────────────────────────────
#&gt; Delimiter: &quot;,&quot;
#&gt; chr  (7): country, iso2c, iso3c, region, capital, income...
#&gt; dbl  (9): year, gdpPcap, lifeExp, pop, research, militar...
#&gt; lgl  (1): status
#&gt; date (1): lastupdated
#&gt; 
#&gt; ℹ Use `spec()` to retrieve the full column specification for this data.
#&gt; ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="modeling.html#cb238-1" tabindex="-1"></a>wdi_world</span>
<span id="cb238-2"><a href="modeling.html#cb238-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 8,778 × 18</span></span>
<span id="cb238-3"><a href="modeling.html#cb238-3" tabindex="-1"></a><span class="co">#&gt;    country     iso2c iso3c  year status lastupdated gdpPcap</span></span>
<span id="cb238-4"><a href="modeling.html#cb238-4" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;lgl&gt;  &lt;date&gt;        &lt;dbl&gt;</span></span>
<span id="cb238-5"><a href="modeling.html#cb238-5" tabindex="-1"></a><span class="co">#&gt;  1 Afghanistan AF    AFG    1990 NA     2023-07-25      NA </span></span>
<span id="cb238-6"><a href="modeling.html#cb238-6" tabindex="-1"></a><span class="co">#&gt;  2 Afghanistan AF    AFG    1991 NA     2023-07-25      NA </span></span>
<span id="cb238-7"><a href="modeling.html#cb238-7" tabindex="-1"></a><span class="co">#&gt;  3 Afghanistan AF    AFG    1993 NA     2023-07-25      NA </span></span>
<span id="cb238-8"><a href="modeling.html#cb238-8" tabindex="-1"></a><span class="co">#&gt;  4 Afghanistan AF    AFG    2015 NA     2023-07-25     592.</span></span>
<span id="cb238-9"><a href="modeling.html#cb238-9" tabindex="-1"></a><span class="co">#&gt;  5 Afghanistan AF    AFG    1999 NA     2023-07-25      NA </span></span>
<span id="cb238-10"><a href="modeling.html#cb238-10" tabindex="-1"></a><span class="co">#&gt;  6 Afghanistan AF    AFG    1992 NA     2023-07-25      NA </span></span>
<span id="cb238-11"><a href="modeling.html#cb238-11" tabindex="-1"></a><span class="co">#&gt;  7 Afghanistan AF    AFG    1996 NA     2023-07-25      NA </span></span>
<span id="cb238-12"><a href="modeling.html#cb238-12" tabindex="-1"></a><span class="co">#&gt;  8 Afghanistan AF    AFG    1997 NA     2023-07-25      NA </span></span>
<span id="cb238-13"><a href="modeling.html#cb238-13" tabindex="-1"></a><span class="co">#&gt;  9 Afghanistan AF    AFG    2002 NA     2023-07-25     360.</span></span>
<span id="cb238-14"><a href="modeling.html#cb238-14" tabindex="-1"></a><span class="co">#&gt; 10 Afghanistan AF    AFG    2013 NA     2023-07-25     608.</span></span>
<span id="cb238-15"><a href="modeling.html#cb238-15" tabindex="-1"></a><span class="co">#&gt; # ℹ 8,768 more rows</span></span>
<span id="cb238-16"><a href="modeling.html#cb238-16" tabindex="-1"></a><span class="co">#&gt; # ℹ 11 more variables: lifeExp &lt;dbl&gt;, pop &lt;dbl&gt;,</span></span>
<span id="cb238-17"><a href="modeling.html#cb238-17" tabindex="-1"></a><span class="co">#&gt; #   research &lt;dbl&gt;, military &lt;dbl&gt;, education &lt;dbl&gt;,</span></span>
<span id="cb238-18"><a href="modeling.html#cb238-18" tabindex="-1"></a><span class="co">#&gt; #   region &lt;chr&gt;, capital &lt;chr&gt;, longitude &lt;dbl&gt;,</span></span>
<span id="cb238-19"><a href="modeling.html#cb238-19" tabindex="-1"></a><span class="co">#&gt; #   latitude &lt;dbl&gt;, income &lt;chr&gt;, lending &lt;chr&gt;</span></span></code></pre></div>
<p>SE.XPD.TOTL.GB.ZS: Government expenditure on education, total (% of government expenditure)
SE.XPD.TOTL.GD.ZS: Government expenditure on education, total (% of GDP)
SE.XPD.PRIM.PC.ZS: Government expenditure per student, primary (% of GDP per capita)
MS.MIL.XPND.ZS: Military expenditure (% of general government expenditure)
SE.XPD.TERT.ZS: Expenditure on tertiary education (% of government expenditure on education)</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="modeling.html#cb239-1" tabindex="-1"></a>mod_e <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> education, wdi_world); mod_e</span>
<span id="cb239-2"><a href="modeling.html#cb239-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb239-3"><a href="modeling.html#cb239-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb239-4"><a href="modeling.html#cb239-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = lifeExp ~ education, data = wdi_world)</span></span>
<span id="cb239-5"><a href="modeling.html#cb239-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb239-6"><a href="modeling.html#cb239-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb239-7"><a href="modeling.html#cb239-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)    education  </span></span>
<span id="cb239-8"><a href="modeling.html#cb239-8" tabindex="-1"></a><span class="co">#&gt;     66.7431       0.7654</span></span></code></pre></div>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="modeling.html#cb240-1" tabindex="-1"></a>wdi_world <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(education, lifeExp)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>)</span>
<span id="cb240-2"><a href="modeling.html#cb240-2" tabindex="-1"></a><span class="co">#&gt; Warning: Removed 4030 rows containing non-finite values</span></span>
<span id="cb240-3"><a href="modeling.html#cb240-3" tabindex="-1"></a><span class="co">#&gt; (`stat_smooth()`).</span></span>
<span id="cb240-4"><a href="modeling.html#cb240-4" tabindex="-1"></a><span class="co">#&gt; Warning: Removed 4030 rows containing missing values</span></span>
<span id="cb240-5"><a href="modeling.html#cb240-5" tabindex="-1"></a><span class="co">#&gt; (`geom_point()`).</span></span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="modeling.html#cb241-1" tabindex="-1"></a>wdi_world <span class="sc">%&gt;%</span> <span class="fu">filter</span>(income <span class="sc">!=</span> <span class="st">&quot;Aggregates&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(education, lifeExp) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(education, lifeExp)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="modeling.html#cb242-1" tabindex="-1"></a>wdi_world_el <span class="ot">&lt;-</span> wdi_world <span class="sc">%&gt;%</span> <span class="fu">select</span>(country, year, education, lifeExp, gdpPcap, pop, research, military, region, income) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(income <span class="sc">!=</span> <span class="st">&quot;Aggregates&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(education, lifeExp)</span></code></pre></div>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="modeling.html#cb243-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(education)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb243-2"><a href="modeling.html#cb243-2" tabindex="-1"></a><span class="co">#&gt; `stat_bin()` using `bins = 30`. Pick better value with</span></span>
<span id="cb243-3"><a href="modeling.html#cb243-3" tabindex="-1"></a><span class="co">#&gt; `binwidth`.</span></span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="modeling.html#cb244-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year<span class="sc">==</span><span class="dv">2020</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> education, <span class="at">fill =</span> income)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="28-modeling_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="modeling.html#cb245-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year<span class="sc">==</span><span class="dv">2020</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(education))</span>
<span id="cb245-2"><a href="modeling.html#cb245-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 156 × 10</span></span>
<span id="cb245-3"><a href="modeling.html#cb245-3" tabindex="-1"></a><span class="co">#&gt;    country    year education lifeExp gdpPcap    pop research</span></span>
<span id="cb245-4"><a href="modeling.html#cb245-4" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span id="cb245-5"><a href="modeling.html#cb245-5" tabindex="-1"></a><span class="co">#&gt;  1 Marshall…  2020     13.6     65.0   5041. 4.34e4   NA    </span></span>
<span id="cb245-6"><a href="modeling.html#cb245-6" tabindex="-1"></a><span class="co">#&gt;  2 Solomon …  2020     12.8     70.2   2080. 6.91e5   NA    </span></span>
<span id="cb245-7"><a href="modeling.html#cb245-7" tabindex="-1"></a><span class="co">#&gt;  3 Bolivia    2020      9.84    64.5   2920. 1.19e7   NA    </span></span>
<span id="cb245-8"><a href="modeling.html#cb245-8" tabindex="-1"></a><span class="co">#&gt;  4 Namibia    2020      9.45    62.8   4152. 2.49e6   NA    </span></span>
<span id="cb245-9"><a href="modeling.html#cb245-9" tabindex="-1"></a><span class="co">#&gt;  5 Sierra L…  2020      8.81    59.8    608. 8.23e6   NA    </span></span>
<span id="cb245-10"><a href="modeling.html#cb245-10" tabindex="-1"></a><span class="co">#&gt;  6 Botswana   2020      8.74    65.6   5811. 2.55e6   NA    </span></span>
<span id="cb245-11"><a href="modeling.html#cb245-11" tabindex="-1"></a><span class="co">#&gt;  7 Saudi Ar…  2020      7.81    76.2  18857. 3.60e7    0.522</span></span>
<span id="cb245-12"><a href="modeling.html#cb245-12" tabindex="-1"></a><span class="co">#&gt;  8 Iceland    2020      7.72    83.1  52442. 3.66e5    2.47 </span></span>
<span id="cb245-13"><a href="modeling.html#cb245-13" tabindex="-1"></a><span class="co">#&gt;  9 Lesotho    2020      7.67    54.7    969. 2.25e6   NA    </span></span>
<span id="cb245-14"><a href="modeling.html#cb245-14" tabindex="-1"></a><span class="co">#&gt; 10 Cabo Ver…  2020      7.58    74.8   2950. 5.83e5   NA    </span></span>
<span id="cb245-15"><a href="modeling.html#cb245-15" tabindex="-1"></a><span class="co">#&gt; # ℹ 146 more rows</span></span>
<span id="cb245-16"><a href="modeling.html#cb245-16" tabindex="-1"></a><span class="co">#&gt; # ℹ 3 more variables: military &lt;dbl&gt;, region &lt;chr&gt;,</span></span>
<span id="cb245-17"><a href="modeling.html#cb245-17" tabindex="-1"></a><span class="co">#&gt; #   income &lt;chr&gt;</span></span></code></pre></div>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="modeling.html#cb246-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year<span class="sc">==</span><span class="dv">2020</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(education))</span>
<span id="cb246-2"><a href="modeling.html#cb246-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 156 × 10</span></span>
<span id="cb246-3"><a href="modeling.html#cb246-3" tabindex="-1"></a><span class="co">#&gt;    country    year education lifeExp gdpPcap    pop research</span></span>
<span id="cb246-4"><a href="modeling.html#cb246-4" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span id="cb246-5"><a href="modeling.html#cb246-5" tabindex="-1"></a><span class="co">#&gt;  1 Marshall…  2020     13.6     65.0   5041. 4.34e4   NA    </span></span>
<span id="cb246-6"><a href="modeling.html#cb246-6" tabindex="-1"></a><span class="co">#&gt;  2 Solomon …  2020     12.8     70.2   2080. 6.91e5   NA    </span></span>
<span id="cb246-7"><a href="modeling.html#cb246-7" tabindex="-1"></a><span class="co">#&gt;  3 Bolivia    2020      9.84    64.5   2920. 1.19e7   NA    </span></span>
<span id="cb246-8"><a href="modeling.html#cb246-8" tabindex="-1"></a><span class="co">#&gt;  4 Namibia    2020      9.45    62.8   4152. 2.49e6   NA    </span></span>
<span id="cb246-9"><a href="modeling.html#cb246-9" tabindex="-1"></a><span class="co">#&gt;  5 Sierra L…  2020      8.81    59.8    608. 8.23e6   NA    </span></span>
<span id="cb246-10"><a href="modeling.html#cb246-10" tabindex="-1"></a><span class="co">#&gt;  6 Botswana   2020      8.74    65.6   5811. 2.55e6   NA    </span></span>
<span id="cb246-11"><a href="modeling.html#cb246-11" tabindex="-1"></a><span class="co">#&gt;  7 Saudi Ar…  2020      7.81    76.2  18857. 3.60e7    0.522</span></span>
<span id="cb246-12"><a href="modeling.html#cb246-12" tabindex="-1"></a><span class="co">#&gt;  8 Iceland    2020      7.72    83.1  52442. 3.66e5    2.47 </span></span>
<span id="cb246-13"><a href="modeling.html#cb246-13" tabindex="-1"></a><span class="co">#&gt;  9 Lesotho    2020      7.67    54.7    969. 2.25e6   NA    </span></span>
<span id="cb246-14"><a href="modeling.html#cb246-14" tabindex="-1"></a><span class="co">#&gt; 10 Cabo Ver…  2020      7.58    74.8   2950. 5.83e5   NA    </span></span>
<span id="cb246-15"><a href="modeling.html#cb246-15" tabindex="-1"></a><span class="co">#&gt; # ℹ 146 more rows</span></span>
<span id="cb246-16"><a href="modeling.html#cb246-16" tabindex="-1"></a><span class="co">#&gt; # ℹ 3 more variables: military &lt;dbl&gt;, region &lt;chr&gt;,</span></span>
<span id="cb246-17"><a href="modeling.html#cb246-17" tabindex="-1"></a><span class="co">#&gt; #   income &lt;chr&gt;</span></span></code></pre></div>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="modeling.html#cb247-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year<span class="sc">==</span><span class="dv">2020</span>) <span class="sc">%&gt;%</span> <span class="fu">lm</span>(gdpPcap <span class="sc">~</span> education, .)</span>
<span id="cb247-2"><a href="modeling.html#cb247-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb247-3"><a href="modeling.html#cb247-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb247-4"><a href="modeling.html#cb247-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = gdpPcap ~ education, data = .)</span></span>
<span id="cb247-5"><a href="modeling.html#cb247-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb247-6"><a href="modeling.html#cb247-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb247-7"><a href="modeling.html#cb247-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)    education  </span></span>
<span id="cb247-8"><a href="modeling.html#cb247-8" tabindex="-1"></a><span class="co">#&gt;     10568.8        940.2</span></span></code></pre></div>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="modeling.html#cb248-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year<span class="sc">==</span><span class="dv">2020</span>) <span class="sc">%&gt;%</span> <span class="fu">lm</span>(gdpPcap <span class="sc">~</span> education, .) <span class="sc">%&gt;%</span> <span class="fu">glance</span>()</span>
<span id="cb248-2"><a href="modeling.html#cb248-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1 × 12</span></span>
<span id="cb248-3"><a href="modeling.html#cb248-3" tabindex="-1"></a><span class="co">#&gt;   r.squared adj.r.squared  sigma statistic p.value    df</span></span>
<span id="cb248-4"><a href="modeling.html#cb248-4" tabindex="-1"></a><span class="co">#&gt;       &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span id="cb248-5"><a href="modeling.html#cb248-5" tabindex="-1"></a><span class="co">#&gt; 1   0.00815       0.00166 20342.      1.26   0.264     1</span></span>
<span id="cb248-6"><a href="modeling.html#cb248-6" tabindex="-1"></a><span class="co">#&gt; # ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,</span></span>
<span id="cb248-7"><a href="modeling.html#cb248-7" tabindex="-1"></a><span class="co">#&gt; #   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</span></span></code></pre></div>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="modeling.html#cb249-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> education <span class="sc">+</span> research <span class="sc">+</span> military, .) <span class="sc">%&gt;%</span> <span class="fu">glance</span>()</span>
<span id="cb249-2"><a href="modeling.html#cb249-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1 × 12</span></span>
<span id="cb249-3"><a href="modeling.html#cb249-3" tabindex="-1"></a><span class="co">#&gt;   r.squared adj.r.squared sigma statistic   p.value    df</span></span>
<span id="cb249-4"><a href="modeling.html#cb249-4" tabindex="-1"></a><span class="co">#&gt;       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span id="cb249-5"><a href="modeling.html#cb249-5" tabindex="-1"></a><span class="co">#&gt; 1     0.346         0.345  5.25      269. 2.26e-140     3</span></span>
<span id="cb249-6"><a href="modeling.html#cb249-6" tabindex="-1"></a><span class="co">#&gt; # ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,</span></span>
<span id="cb249-7"><a href="modeling.html#cb249-7" tabindex="-1"></a><span class="co">#&gt; #   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</span></span></code></pre></div>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="modeling.html#cb250-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> education <span class="sc">+</span> research <span class="sc">+</span> military, .) <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb250-2"><a href="modeling.html#cb250-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 4 × 5</span></span>
<span id="cb250-3"><a href="modeling.html#cb250-3" tabindex="-1"></a><span class="co">#&gt;   term        estimate std.error statistic   p.value</span></span>
<span id="cb250-4"><a href="modeling.html#cb250-4" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span id="cb250-5"><a href="modeling.html#cb250-5" tabindex="-1"></a><span class="co">#&gt; 1 (Intercept)  70.2       0.489    143.    0        </span></span>
<span id="cb250-6"><a href="modeling.html#cb250-6" tabindex="-1"></a><span class="co">#&gt; 2 education     0.0767    0.0966     0.794 4.27e-  1</span></span>
<span id="cb250-7"><a href="modeling.html#cb250-7" tabindex="-1"></a><span class="co">#&gt; 3 research      3.84      0.146     26.4   7.42e-127</span></span>
<span id="cb250-8"><a href="modeling.html#cb250-8" tabindex="-1"></a><span class="co">#&gt; 4 military     -0.0683    0.102     -0.669 5.04e-  1</span></span></code></pre></div>
<p><span class="math display">\[lifeExp \sim 70.22 + 0.08\cdot education + 3.84 \cdot research - 0.07 \cdot military\]</span></p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="modeling.html#cb251-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">lm</span>(gdpPcap <span class="sc">~</span> education <span class="sc">+</span> research <span class="sc">+</span> military, .) <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb251-2"><a href="modeling.html#cb251-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 4 × 5</span></span>
<span id="cb251-3"><a href="modeling.html#cb251-3" tabindex="-1"></a><span class="co">#&gt;   term        estimate std.error statistic   p.value</span></span>
<span id="cb251-4"><a href="modeling.html#cb251-4" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span id="cb251-5"><a href="modeling.html#cb251-5" tabindex="-1"></a><span class="co">#&gt; 1 (Intercept)    1061.     1310.     0.810 4.18e-  1</span></span>
<span id="cb251-6"><a href="modeling.html#cb251-6" tabindex="-1"></a><span class="co">#&gt; 2 education      1332.      259.     5.15  3.01e-  7</span></span>
<span id="cb251-7"><a href="modeling.html#cb251-7" tabindex="-1"></a><span class="co">#&gt; 3 research      12783.      390.    32.8   4.69e-179</span></span>
<span id="cb251-8"><a href="modeling.html#cb251-8" tabindex="-1"></a><span class="co">#&gt; 4 military       -964.      273.    -3.53  4.35e-  4</span></span></code></pre></div>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="modeling.html#cb252-1" tabindex="-1"></a>wdi_world_el <span class="sc">%&gt;%</span> <span class="fu">lm</span>(gdpPcap <span class="sc">~</span> education <span class="sc">+</span> research <span class="sc">+</span> military, .) <span class="sc">%&gt;%</span> <span class="fu">glance</span>()</span>
<span id="cb252-2"><a href="modeling.html#cb252-2" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1 × 12</span></span>
<span id="cb252-3"><a href="modeling.html#cb252-3" tabindex="-1"></a><span class="co">#&gt;   r.squared adj.r.squared  sigma statistic   p.value    df</span></span>
<span id="cb252-4"><a href="modeling.html#cb252-4" tabindex="-1"></a><span class="co">#&gt;       &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span id="cb252-5"><a href="modeling.html#cb252-5" tabindex="-1"></a><span class="co">#&gt; 1     0.477         0.476 14036.      464. 3.75e-214     3</span></span>
<span id="cb252-6"><a href="modeling.html#cb252-6" tabindex="-1"></a><span class="co">#&gt; # ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,</span></span>
<span id="cb252-7"><a href="modeling.html#cb252-7" tabindex="-1"></a><span class="co">#&gt; #   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</span></span></code></pre></div>
<p><span class="math display">\[gdpPcap \sim 1077 + 1024\cdot education + 12792 \cdot research - 967 \cdot military\]</span></p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="modeling.html#cb253-1" tabindex="-1"></a>mod_r <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> research, wdi_world); mod_e</span>
<span id="cb253-2"><a href="modeling.html#cb253-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb253-3"><a href="modeling.html#cb253-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb253-4"><a href="modeling.html#cb253-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = lifeExp ~ education, data = wdi_world)</span></span>
<span id="cb253-5"><a href="modeling.html#cb253-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb253-6"><a href="modeling.html#cb253-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb253-7"><a href="modeling.html#cb253-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)    education  </span></span>
<span id="cb253-8"><a href="modeling.html#cb253-8" tabindex="-1"></a><span class="co">#&gt;     66.7431       0.7654</span></span></code></pre></div>
</div>
<div id="model-and-linear-regression-quick-reference" class="section level2" number="20.14">
<h2><span class="header-section-number">20.14</span> model and Linear Regression Quick Reference</h2>
<ul>
<li>R4DS: Model basics
<ul>
<li><a href="https://r4ds.had.co.nz/model-basics.html" class="uri">https://r4ds.had.co.nz/model-basics.html</a></li>
</ul></li>
</ul>
<p>For explanation of other indices, please see.</p>
<ul>
<li>r-statistics.co by Selva Prabhakaran:
<ul>
<li><a href="http://r-statistics.co/Linear-Regression.html" class="uri">http://r-statistics.co/Linear-Regression.html</a></li>
</ul></li>
<li>Meaning Behind Each Section of Summary()
<ul>
<li><a href="https://www.learnbymarketing.com/tutorials/explaining-the-lm-summary-in-r/" class="uri">https://www.learnbymarketing.com/tutorials/explaining-the-lm-summary-in-r/</a></li>
</ul></li>
</ul>

</div>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>データサイエンスをはじめましょう<br />
- Data Science for All -</strong>" was written by 鈴木寛（Hirosi Suzuki）. It was last built on 2023-09-05.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
